command! Vythonautos normal :call Vythonautos()<cr>

nnoremap <silent> <c-F10> :vsp<enter><c-w><c-l>:e ~/pythonbuff.py<cr>:call Vythonload()<cr>:call Vythonautos()<cr>:sp<cr>:e test.py<cr><c-w><c-h>:set filetype=python<cr>

func! Vythonautos()

py3 << EOL
import numpy as np
import cv2
import cv2 as cv
import matplotlib.pyplot as plt
import bokeh
import pickle
import os
import re
import sys
import pandas as pd
from glob import glob
from time import time as now, sleep
import inspect
import pyperclip as pp
import plumbum as pb

from numpy import array, linspace, exp, amin, amax, sum as Σ, mean as μ, sin, cos, tan, log, log10, meshgrid, zeros, ones, append, dot, pi, pi as π, sqrt, arange
from numpy.linalg import norm
# inspect.getmodule(zeros)

from matplotlib.pyplot import figure, plot, imshow, show, grid, xlabel, ylabel, title, draw, legend

from shutil import copyfile as cp

cmd = pb.cmd

def ls(*args):
    return [r for r in pb.cmd.ls(args).split('\n') if len(r) > 0]

def mshow(*args, **kwargs):
    h = figure()
    imshow(*args, **kwargs)
    if '__nvim__' not in globals() or __nvim__ == False:
        show(block=False)
    else:
        show()
    return h

def mplot(*args, **kwargs):
    h = figure()
    plot(*args, **kwargs)
    grid()
    if '__nvim__' not in globals() or __nvim__ == False:
        show(block=False)
    else:
        show()
    return h

def mread(fname):
    with open(fname, 'r') as f:
        dat = f.read().split('\n')
    return dat

def pdump(fname, dat):
    with open(fname, 'wb') as f:
        pickle.dump(dat, f)

def pload(fname):
    with open(fname, 'rb') as f:
        dat = pickle.load(f)
    return dat

def toarray(*args):
    if len(args) == 1 and type(args[0]) is list:
        return np.array(args[0])
    return np.array(args)
 
def Copy(dat):
    pp.copy(str(dat))

def Paste():
    return pp.paste()


def rotate_image(img, angle):
    size_reverse = np.array(img.shape[1::-1]) # swap x with y
    M = cv.getRotationMatrix2D(tuple(size_reverse / 2.), angle, 1.)
    MM = np.absolute(M[:,:2])
    size_new = MM @ size_reverse
    M[:,-1] += (size_new - size_reverse) / 2.
    return cv.warpAffine(img, M, tuple(size_new.astype(int)))

def loadenvvariables():
    for envvar in list(os.environ.keys()):
        if envvar:
            globals()[envvar] = os.environ[envvar]

def runfile(filename):
    with open(filename) as f:
        exec(f.read())
    temp = locals()
    for k in temp.keys():
        globals()[k] = temp[k]

def runfbackg(filename):
    t = threading.Thread(target=runfile, args=(filename,))
    t.start()


import bokeh.plotting as bplotting
import bokeh.models.tools as btools
def bplot(x=None, y=None, outfile=None, title='', xlab='', ylab='', legend=None,
         linew=2, pwidth=1280, pheight=720):
    if not outfile:
        outfile = f"{vyth.hometmp}{np.random.randint(10000000)}.html"
    if not y:
        y = np.array(x).copy()
        x = np.arange(len(x))
    bplotting.output_file(outfile)
    p = bplotting.figure(title=title, x_axis_label=xlab, y_axis_label=ylab)
    if legend:
        p.line(x,y, legend=legend, line_width=linew)
    else:
        p.line(x,y, line_width=linew)
    p.add_tools(btools.HoverTool())
    p.toolbar.logo = None #don't show Bokeh icon/link
    bplotting.save(p)
    vyth.writebuffhtml(f'<object data="{outfile}" width="{pwidth}" height="{pheight}"></object>',
                       br=3, shownum=True)
    
def bimagesc(data, outfile=None, title='', xlab='', ylab='', pwidth=1280, pheight=720):
    if not outfile:
        outfile = f"{vyth.hometmp}{np.random.randint(10000000)}.html"
    bplotting.output_file(outfile)
    p = bplotting.figure(title=title, x_axis_label=xlab, y_axis_label=ylab)
    p.image(image=[data], x=0, y=0, dw=data.shape[1], dh=data.shape[0], palette='Spectral11')
    p.add_tools(btools.HoverTool())
    p.toolbar.logo = None #don't show Bokeh icon/link
    bplotting.save(p)
    vyth.writebuffhtml(f'<object data="{outfile}" width="{pwidth}" height="{pheight}"></object>',
                       br=3, shownum=True)

def bimshow(img_orig, scale=1, **figure_kwargs):
    outfile = f"{vyth.hometmp}{np.random.randint(10000000)}.html"
    bplotting.output_file(outfile)
    img = img_orig.astype(np.uint8)
    if img.ndim == 2:  # gray input
        img = cv.cvtColor(img, cv.COLOR_GRAY2RGBA)
    elif img.ndim == 3:  # rgb input
        img = cv.cvtColor(img, cv.COLOR_BGR2RGBA)
    img = np.ascontiguousarray((img))
    img2 = img.view('uint32').reshape(img.shape[:2])
    p = bplotting.figure(
        x_range=(0, img.shape[1]),
        y_range=(img.shape[0], 0),
        frame_width=img.shape[1]*scale,
        frame_height=img.shape[0]*scale,
        **figure_kwargs)
    p.add_tools(btools.HoverTool(
        tooltips=[
            ("(x, y)", "($x, $y)"),
            ("RGB", "(@R, @G, @B)")]))
    p.toolbar.logo = None #don't show Bokeh icon/link
    source = bplotting.ColumnDataSource(data=dict(
        img=[img2], x=[0], y=[0],
        dw=[img.shape[1]], dh=[img.shape[0]],
        R=[img[::-1, :, 0]], G=[img[::-1, :, 1]], B=[img[::-1, :, 2]]))
    p.image_rgba(source=source, image='img', x='x', y='y', dw='dw', dh='dh')
    bplotting.save(p)  # open a browser
    vyth.writebuffhtml(f'<object data="{outfile}" width="{img.shape[1]+100}" height="{img.shape[0]+100}"></object>',  br=3, shownum=True)

EOL


"easier unicode inputs
inoremap \exclamdown ¡
inoremap \sterling £
inoremap \yen ¥
inoremap \brokenbar ¦
inoremap \S §
inoremap \copyright ©
inoremap \ordfeminine ª
inoremap \neg ¬
inoremap \circledR ®
inoremap \highminus ¯
inoremap \degree °
inoremap \pm ±
inoremap \^2 ²
inoremap \^3 ³
inoremap \P ¶
inoremap \cdotp ·
inoremap \^1 ¹
inoremap \ordmasculine º
inoremap \1/4 ¼
inoremap \1/2 ½
inoremap \3/4 ¾
inoremap \questiondown ¿
inoremap \AA Å
inoremap \AE Æ
inoremap \DH Ð
inoremap \times ×
inoremap \O Ø
inoremap \TH Þ
inoremap \ss ß
inoremap \aa å
inoremap \ae æ
inoremap \eth ð
inoremap \div ÷
inoremap \o ø
inoremap \th þ
inoremap \DJ Đ
inoremap \dj đ
inoremap \hbar ħ
inoremap \imath ı
inoremap \L Ł
inoremap \l ł
inoremap \NG Ŋ
inoremap \ng ŋ
inoremap \OE Œ
inoremap \oe œ
inoremap \hvlig ƕ
inoremap \nrleg ƞ
inoremap \Zbar Ƶ
inoremap \doublepipe ǂ
inoremap \jmath ȷ
inoremap \trna ɐ
inoremap \trnsa ɒ
inoremap \openo ɔ
inoremap \rtld ɖ
inoremap \schwa ə
inoremap \pgamma ɣ
inoremap \pbgam ɤ
inoremap \trnh ɥ
inoremap \btdl ɬ
inoremap \rtll ɭ
inoremap \trnm ɯ
inoremap \trnmlr ɰ
inoremap \ltlmr ɱ
inoremap \ltln ɲ
inoremap \rtln ɳ
inoremap \clomeg ɷ
inoremap \ltphi ɸ
inoremap \trnr ɹ
inoremap \trnrl ɺ
inoremap \rttrnr ɻ
inoremap \rl ɼ
inoremap \rtlr ɽ
inoremap \fhr ɾ
inoremap \rtls ʂ
inoremap \esh ʃ
inoremap \trnt ʇ
inoremap \rtlt ʈ
inoremap \pupsil ʊ
inoremap \pscrv ʋ
inoremap \invv ʌ
inoremap \invw ʍ
inoremap \trny ʎ
inoremap \rtlz ʐ
inoremap \yogh ʒ
inoremap \glst ʔ
inoremap \reglst ʕ
inoremap \inglst ʖ
inoremap \turnk ʞ
inoremap \dyogh ʤ
inoremap \tesh ʧ
inoremap \^h ʰ
inoremap \^j ʲ
inoremap \^r ʳ
inoremap \^w ʷ
inoremap \^y ʸ
inoremap \rasp ʼ
inoremap \verts ˈ
inoremap \verti ˌ
inoremap \lmrk ː
inoremap \hlmrk ˑ
inoremap \sbrhr ˒
inoremap \sblhr ˓
inoremap \rais ˔
inoremap \low ˕
inoremap \u ˘
inoremap \tildelow ˜
inoremap \^l ˡ
inoremap \^s ˢ
inoremap \^x ˣ
inoremap   \grave              ̀ 
inoremap   \acute              ́ 
inoremap   \hat                ̂ 
inoremap   \tilde              ̃ 
inoremap   \bar                ̄ 
inoremap   \overbar            ̅ 
inoremap   \breve              ̆ 
inoremap   \dot                ̇ 
inoremap   \ddot               ̈ 
inoremap   \ovhook             ̉ 
inoremap   \ocirc              ̊ 
inoremap   \H                  ̋ 
inoremap   \check              ̌ 
inoremap   \candra             ̐ 
inoremap   \oturnedcomma       ̒ 
inoremap   \ocommatopright     ̕ 
inoremap   \droang             ̚ 
inoremap   \palh               ̡ 
inoremap   \rh                 ̢ 
inoremap   \c                  ̧ 
inoremap   \k                  ̨ 
inoremap   \sbbrg              ̪ 
inoremap   \wideutilde         ̰ 
inoremap   \underbar           ̲ 
inoremap   \strike             ̶ 
inoremap   \not                ̸ 
inoremap   \underleftrightarro ͍ w
inoremap \Alpha Α
inoremap \Beta Β
inoremap \Gamma Γ
inoremap \Delta Δ
inoremap \Epsilon Ε
inoremap \Zeta Ζ
inoremap \Eta Η
inoremap \Theta Θ
inoremap \Iota Ι
inoremap \Kappa Κ
inoremap \Lambda Λ
inoremap \upMu Μ
inoremap \upNu Ν
inoremap \Xi Ξ
inoremap \upOmicron Ο
inoremap \Pi Π
inoremap \Rho Ρ
inoremap \Sigma Σ
inoremap \Tau Τ
inoremap \Upsilon Υ
inoremap \Phi Φ
inoremap \Chi Χ
inoremap \Psi Ψ
inoremap \Omega Ω
inoremap \alpha α
inoremap \beta β
inoremap \gamma γ
inoremap \delta δ
inoremap \upepsilon ε
inoremap \zeta ζ
inoremap \eta η
inoremap \theta θ
inoremap \iota ι
inoremap \kappa κ
inoremap \lambda λ
inoremap \mu μ
inoremap \nu ν
inoremap \xi ξ
inoremap \upomicron ο
inoremap \pi π
inoremap \rho ρ
inoremap \varsigma ς
inoremap \sigma σ
inoremap \tau τ
inoremap \upsilon υ
inoremap \varphi φ
inoremap \chi χ
inoremap \psi ψ
inoremap \omega ω
inoremap \upvarbeta ϐ
inoremap \vartheta ϑ
inoremap \phi ϕ
inoremap \varpi ϖ
inoremap \upoldKoppa Ϙ
inoremap \upoldkoppa ϙ
inoremap \Stigma Ϛ
inoremap \upstigma ϛ
inoremap \Digamma Ϝ
inoremap \digamma ϝ
inoremap \Koppa Ϟ
inoremap \upkoppa ϟ
inoremap \Sampi Ϡ
inoremap \upsampi ϡ
inoremap \varkappa ϰ
inoremap \varrho ϱ
inoremap \varTheta ϴ
inoremap \epsilon ϵ
inoremap \backepsilon ϶
inoremap \^A ᴬ
inoremap \^B ᴮ
inoremap \^D ᴰ
inoremap \^E ᴱ
inoremap \^G ᴳ
inoremap \^H ᴴ
inoremap \^I ᴵ
inoremap \^J ᴶ
inoremap \^K ᴷ
inoremap \^L ᴸ
inoremap \^M ᴹ
inoremap \^N ᴺ
inoremap \^O ᴼ
inoremap \^P ᴾ
inoremap \^R ᴿ
inoremap \^T ᵀ
inoremap \^U ᵁ
inoremap \^W ᵂ
inoremap \^a ᵃ
inoremap \^alpha ᵅ
inoremap \^b ᵇ
inoremap \^d ᵈ
inoremap \^e ᵉ
inoremap \^epsilon ᵋ
inoremap \^g ᵍ
inoremap \^k ᵏ
inoremap \^m ᵐ
inoremap \^o ᵒ
inoremap \^p ᵖ
inoremap \^t ᵗ
inoremap \^u ᵘ
inoremap \^v ᵛ
inoremap \^beta ᵝ
inoremap \^gamma ᵞ
inoremap \^delta ᵟ
inoremap \^phi ᵠ
inoremap \^chi ᵡ
inoremap \_i ᵢ
inoremap \_r ᵣ
inoremap \_u ᵤ
inoremap \_v ᵥ
inoremap \_beta ᵦ
inoremap \_gamma ᵧ
inoremap \_rho ᵨ
inoremap \_phi ᵩ
inoremap \_chi ᵪ
inoremap \^c ᶜ
inoremap \^f ᶠ
inoremap \^iota ᶥ
inoremap \^ltphi ᶲ
inoremap \^z ᶻ
inoremap \^theta ᶿ
inoremap \enspace  
inoremap \quad  
inoremap \thickspace  
inoremap \thinspace  
inoremap \hspace  
inoremap \endash –
inoremap \emdash —
inoremap \Vert ‖
inoremap \lq ‘
inoremap \rq ’
inoremap \reapos ‛
inoremap \ldq “
inoremap \rdq ”
inoremap \dagger †
inoremap \ddagger ‡
inoremap \bullet •
inoremap \dots …
inoremap \perthousand ‰
inoremap \pertenthousand ‱
inoremap \prime ′
inoremap \pprime ″
inoremap \ppprime ‴
inoremap \backprime ‵
inoremap \backpprime ‶
inoremap \backppprime ‷
inoremap \guilsinglleft ‹
inoremap \guilsinglright ›
inoremap \:bangbang: ‼
inoremap \tieconcat ⁀
inoremap \:interrobang: ⁉
inoremap \pppprime ⁗
inoremap \tricolon ⁝
inoremap \nolinebreak ⁠
inoremap \^0 ⁰
inoremap \^i ⁱ
inoremap \^4 ⁴
inoremap \^5 ⁵
inoremap \^6 ⁶
inoremap \^7 ⁷
inoremap \^8 ⁸
inoremap \^9 ⁹
inoremap \^+ ⁺
inoremap \^- ⁻
inoremap \^= ⁼
inoremap \^( ⁽
inoremap \^) ⁾
inoremap \^n ⁿ
inoremap \_0 ₀
inoremap \_1 ₁
inoremap \_2 ₂
inoremap \_3 ₃
inoremap \_4 ₄
inoremap \_5 ₅
inoremap \_6 ₆
inoremap \_7 ₇
inoremap \_8 ₈
inoremap \_9 ₉
inoremap \_+ ₊
inoremap \_- ₋
inoremap \_= ₌
inoremap \_( ₍
inoremap \_) ₎
inoremap \_a ₐ
inoremap \_e ₑ
inoremap \_o ₒ
inoremap \_x ₓ
inoremap \_schwa ₔ
inoremap \_h ₕ
inoremap \_k ₖ
inoremap \_l ₗ
inoremap \_m ₘ
inoremap \_n ₙ
inoremap \_p ₚ
inoremap \_s ₛ
inoremap \_t ₜ
inoremap \pes ₧
inoremap \euro €
inoremap \leftharpoonaccent       ⃐ 
inoremap \rightharpoonaccent      ⃑ 
inoremap \vertoverlay             ⃒ 
inoremap \overleftarrow           ⃖ 
inoremap \vec                     ⃗ 
inoremap \dddot                   ⃛ 
inoremap \ddddot                  ⃜ 
inoremap \enclosecircle           ⃝ 
inoremap \enclosesquare           ⃞ 
inoremap \enclosediamond          ⃟ 
inoremap \overleftrightarrow      ⃡ 
inoremap \enclosetriangle         ⃤ 
inoremap \annuity                 ⃧ 
inoremap \threeunderdot           ⃨ 
inoremap \widebridgeabove         ⃩ 
inoremap \underrightharpoondown   ⃬ 
inoremap \underleftharpoondown    ⃭ 
inoremap \underleftarrow          ⃮ 
inoremap \underrightarrow         ⃯ 
inoremap \asteraccent             ⃰ 
inoremap \bbC ℂ
inoremap \eulermascheroni ℇ
inoremap \scrg ℊ
inoremap \scrH ℋ
inoremap \frakH ℌ
inoremap \bbH ℍ
inoremap \planck ℎ
inoremap \hslash ℏ
inoremap \scrI ℐ
inoremap \Im ℑ
inoremap \scrL ℒ
inoremap \ell ℓ
inoremap \bbN ℕ
inoremap \numero №
inoremap \wp ℘
inoremap \bbP ℙ
inoremap \bbQ ℚ
inoremap \scrR ℛ
inoremap \Re ℜ
inoremap \bbR ℝ
inoremap \xrat ℞
inoremap \:tm: ™
inoremap \bbZ ℤ
inoremap \ohm Ω
inoremap \mho ℧
inoremap \frakZ ℨ
inoremap \turnediota ℩
inoremap \Angstrom Å
inoremap \scrB ℬ
inoremap \frakC ℭ
inoremap \euler ℯ
inoremap \scrE ℰ
inoremap \scrF ℱ
inoremap \Finv Ⅎ
inoremap \scrM ℳ
inoremap \scro ℴ
inoremap \aleph ℵ
inoremap \beth ℶ
inoremap \gimel ℷ
inoremap \daleth ℸ
inoremap \:information_source: ℹ
inoremap \bbpi ℼ
inoremap \bbgamma ℽ
inoremap \bbGamma ℾ
inoremap \bbPi ℿ
inoremap \bbsum ⅀
inoremap \Game ⅁
inoremap \sansLturned ⅂
inoremap \sansLmirrored ⅃
inoremap \Yup ⅄
inoremap \bbiD ⅅ
inoremap \bbid ⅆ
inoremap \bbie ⅇ
inoremap \bbii ⅈ
inoremap \bbij ⅉ
inoremap \PropertyLine ⅊
inoremap \upand ⅋
inoremap \1/7 ⅐
inoremap \1/9 ⅑
inoremap \1/10 ⅒
inoremap \1/3 ⅓
inoremap \2/3 ⅔
inoremap \1/5 ⅕
inoremap \2/5 ⅖
inoremap \3/5 ⅗
inoremap \4/5 ⅘
inoremap \1/6 ⅙
inoremap \5/6 ⅚
inoremap \1/8 ⅛
inoremap \3/8 ⅜
inoremap \5/8 ⅝
inoremap \7/8 ⅞
inoremap \1/ ⅟
inoremap \0/3 ↉
inoremap \leftarrow ←
inoremap \uparrow ↑
inoremap \to →
inoremap \rightarrow →
inoremap \downarrow ↓
inoremap \leftrightarrow ↔
inoremap \updownarrow ↕
inoremap \nwarrow ↖
inoremap \nearrow ↗
inoremap \searrow ↘
inoremap \swarrow ↙
inoremap \nleftarrow ↚
inoremap \nrightarrow ↛
inoremap \leftwavearrow ↜
inoremap \rightwavearrow ↝
inoremap \twoheadleftarrow ↞
inoremap \twoheaduparrow ↟
inoremap \twoheadrightarrow ↠
inoremap \twoheaddownarrow ↡
inoremap \leftarrowtail ↢
inoremap \rightarrowtail ↣
inoremap \mapsfrom ↤
inoremap \mapsup ↥
inoremap \mapsto ↦
inoremap \mapsdown ↧
inoremap \updownarrowbar ↨
inoremap \hookleftarrow ↩
inoremap \hookrightarrow ↪
inoremap \looparrowleft ↫
inoremap \looparrowright ↬
inoremap \leftrightsquigarrow ↭
inoremap \nleftrightarrow ↮
inoremap \downzigzagarrow ↯
inoremap \Lsh ↰
inoremap \Rsh ↱
inoremap \Ldsh ↲
inoremap \Rdsh ↳
inoremap \linefeed ↴
inoremap \carriagereturn ↵
inoremap \curvearrowleft ↶
inoremap \curvearrowright ↷
inoremap \barovernorthwestarrow ↸
inoremap \barleftarrowrightarrowbar ↹
inoremap \circlearrowleft ↺
inoremap \circlearrowright ↻
inoremap \leftharpoonup ↼
inoremap \leftharpoondown ↽
inoremap \upharpoonright ↾
inoremap \upharpoonleft ↿
inoremap \rightharpoonup ⇀
inoremap \rightharpoondown ⇁
inoremap \downharpoonright ⇂
inoremap \downharpoonleft ⇃
inoremap \rightleftarrows ⇄
inoremap \dblarrowupdown ⇅
inoremap \leftrightarrows ⇆
inoremap \leftleftarrows ⇇
inoremap \upuparrows ⇈
inoremap \rightrightarrows ⇉
inoremap \downdownarrows ⇊
inoremap \leftrightharpoons ⇋
inoremap \rightleftharpoons ⇌
inoremap \nLeftarrow ⇍
inoremap \nLeftrightarrow ⇎
inoremap \nRightarrow ⇏
inoremap \Leftarrow ⇐
inoremap \Uparrow ⇑
inoremap \Rightarrow ⇒
inoremap \Downarrow ⇓
inoremap \Leftrightarrow ⇔
inoremap \Updownarrow ⇕
inoremap \Nwarrow ⇖
inoremap \Nearrow ⇗
inoremap \Searrow ⇘
inoremap \Swarrow ⇙
inoremap \Lleftarrow ⇚
inoremap \Rrightarrow ⇛
inoremap \leftsquigarrow ⇜
inoremap \rightsquigarrow ⇝
inoremap \nHuparrow ⇞
inoremap \nHdownarrow ⇟
inoremap \leftdasharrow ⇠
inoremap \updasharrow ⇡
inoremap \rightdasharrow ⇢
inoremap \downdasharrow ⇣
inoremap \barleftarrow ⇤
inoremap \rightarrowbar ⇥
inoremap \leftwhitearrow ⇦
inoremap \upwhitearrow ⇧
inoremap \rightwhitearrow ⇨
inoremap \downwhitearrow ⇩
inoremap \whitearrowupfrombar ⇪
inoremap \circleonrightarrow ⇴
inoremap \DownArrowUpArrow ⇵
inoremap \rightthreearrows ⇶
inoremap \nvleftarrow ⇷
inoremap \nvrightarrow ⇸
inoremap \nvleftrightarrow ⇹
inoremap \nVleftarrow ⇺
inoremap \nVrightarrow ⇻
inoremap \nVleftrightarrow ⇼
inoremap \leftarrowtriangle ⇽
inoremap \rightarrowtriangle ⇾
inoremap \leftrightarrowtriangle ⇿
inoremap \forall ∀
inoremap \complement ∁
inoremap \partial ∂
inoremap \exists ∃
inoremap \nexists ∄
inoremap \varnothing ∅
inoremap \increment ∆
inoremap \nabla ∇
inoremap \del ∇
inoremap \in ∈
inoremap \notin ∉
inoremap \smallin ∊
inoremap \ni ∋
inoremap \nni ∌
inoremap \smallni ∍
inoremap \QED ∎
inoremap \prod ∏
inoremap \coprod ∐
inoremap \sum ∑
inoremap \minus −
inoremap \mp ∓
inoremap \dotplus ∔
inoremap \setminus ∖
inoremap \ast ∗
inoremap \circ ∘
inoremap \vysmblkcircle ∙
inoremap \sqrt √
inoremap \cbrt ∛
inoremap \fourthroot ∜
inoremap \propto ∝
inoremap \infty ∞
inoremap \rightangle ∟
inoremap \angle ∠
inoremap \measuredangle ∡
inoremap \sphericalangle ∢
inoremap \mid ∣
inoremap \nmid ∤
inoremap \parallel ∥
inoremap \nparallel ∦
inoremap \wedge ∧
inoremap \vee ∨
inoremap \cap ∩
inoremap \cup ∪
inoremap \union ∪
inoremap \int ∫
inoremap \iint ∬
inoremap \iiint ∭
inoremap \oint ∮
inoremap \oiint ∯
inoremap \oiiint ∰
inoremap \clwintegral ∱
inoremap \varointclockwise ∲
inoremap \ointctrclockwise ∳
inoremap \therefore ∴
inoremap \because ∵
inoremap \Colon ∷
inoremap \dotminus ∸
inoremap \dotsminusdots ∺
inoremap \kernelcontraction ∻
inoremap \sim ∼
inoremap \backsim ∽
inoremap \lazysinv ∾
inoremap \sinewave ∿
inoremap \wr ≀
inoremap \nsim ≁
inoremap \eqsim ≂
inoremap \neqsim ≂̸
inoremap \simeq ≃
inoremap \nsime ≄
inoremap \cong ≅
inoremap \approxnotequal ≆
inoremap \ncong ≇
inoremap \approx ≈
inoremap \napprox ≉
inoremap \approxeq ≊
inoremap \tildetrpl ≋
inoremap \allequal ≌
inoremap \asymp ≍
inoremap \Bumpeq ≎
inoremap \nBumpeq ≎̸
inoremap \bumpeq ≏
inoremap \nbumpeq ≏̸
inoremap \doteq ≐
inoremap \Doteq ≑
inoremap \fallingdotseq ≒
inoremap \risingdotseq ≓
inoremap \coloneq ≔
inoremap \eqcolon ≕
inoremap \eqcirc ≖
inoremap \circeq ≗
inoremap \arceq ≘
inoremap \wedgeq ≙
inoremap \veeeq ≚
inoremap \starequal ≛
inoremap \triangleq ≜
inoremap \eqdef ≝
inoremap \measeq ≞
inoremap \questeq ≟
inoremap \ne ≠
inoremap \equiv ≡
inoremap \nequiv ≢
inoremap \Equiv ≣
inoremap \le ≤
inoremap \ge ≥
inoremap \leqq ≦
inoremap \geqq ≧
inoremap \lneqq ≨
inoremap \lvertneqq ≨︀
inoremap \gneqq ≩
inoremap \gvertneqq ≩︀
inoremap \ll ≪
inoremap \NotLessLess ≪̸
inoremap \gg ≫
inoremap \NotGreaterGreater ≫̸
inoremap \between ≬
inoremap \nasymp ≭
inoremap \nless ≮
inoremap \ngtr ≯
inoremap \nleq ≰
inoremap \ngeq ≱
inoremap \lesssim ≲
inoremap \gtrsim ≳
inoremap \nlesssim ≴
inoremap \ngtrsim ≵
inoremap \lessgtr ≶
inoremap \gtrless ≷
inoremap \notlessgreater ≸
inoremap \notgreaterless ≹
inoremap \prec ≺
inoremap \succ ≻
inoremap \preccurlyeq ≼
inoremap \succcurlyeq ≽
inoremap \precsim ≾
inoremap \nprecsim ≾̸
inoremap \succsim ≿
inoremap \nsuccsim ≿̸
inoremap \nprec ⊀
inoremap \nsucc ⊁
inoremap \subset ⊂
inoremap \supset ⊃
inoremap \nsubset ⊄
inoremap \nsupset ⊅
inoremap \subseteq ⊆
inoremap \supseteq ⊇
inoremap \nsubseteq ⊈
inoremap \nsupseteq ⊉
inoremap \subsetneq ⊊
inoremap \varsubsetneqq ⊊︀
inoremap \supsetneq ⊋
inoremap \varsupsetneq ⊋︀
inoremap \cupdot ⊍
inoremap \uplus ⊎
inoremap \sqsubset ⊏
inoremap \NotSquareSubset ⊏̸
inoremap \sqsupset ⊐
inoremap \NotSquareSuperset ⊐̸
inoremap \sqsubseteq ⊑
inoremap \sqsupseteq ⊒
inoremap \sqcap ⊓
inoremap \sqcup ⊔
inoremap \oplus ⊕
inoremap \ominus ⊖
inoremap \otimes ⊗
inoremap \oslash ⊘
inoremap \odot ⊙
inoremap \circledcirc ⊚
inoremap \circledast ⊛
inoremap \circledequal ⊜
inoremap \circleddash ⊝
inoremap \boxplus ⊞
inoremap \boxminus ⊟
inoremap \boxtimes ⊠
inoremap \boxdot ⊡
inoremap \vdash ⊢
inoremap \dashv ⊣
inoremap \top ⊤
inoremap \bot ⊥
inoremap \models ⊧
inoremap \vDash ⊨
inoremap \Vdash ⊩
inoremap \Vvdash ⊪
inoremap \VDash ⊫
inoremap \nvdash ⊬
inoremap \nvDash ⊭
inoremap \nVdash ⊮
inoremap \nVDash ⊯
inoremap \prurel ⊰
inoremap \scurel ⊱
inoremap \vartriangleleft ⊲
inoremap \vartriangleright ⊳
inoremap \trianglelefteq ⊴
inoremap \trianglerighteq ⊵
inoremap \original ⊶
inoremap \image ⊷
inoremap \multimap ⊸
inoremap \hermitconjmatrix ⊹
inoremap \intercal ⊺
inoremap \xor ⊻
inoremap \nand ⊼
inoremap \nor ⊽
inoremap \rightanglearc ⊾
inoremap \varlrtriangle ⊿
inoremap \bigwedge ⋀
inoremap \bigvee ⋁
inoremap \bigcap ⋂
inoremap \bigcup ⋃
inoremap \diamond ⋄
inoremap \cdot ⋅
inoremap \star ⋆
inoremap \divideontimes ⋇
inoremap \bowtie ⋈
inoremap \ltimes ⋉
inoremap \rtimes ⋊
inoremap \leftthreetimes ⋋
inoremap \rightthreetimes ⋌
inoremap \backsimeq ⋍
inoremap \curlyvee ⋎
inoremap \curlywedge ⋏
inoremap \Subset ⋐
inoremap \Supset ⋑
inoremap \Cap ⋒
inoremap \Cup ⋓
inoremap \pitchfork ⋔
inoremap \equalparallel ⋕
inoremap \lessdot ⋖
inoremap \gtrdot ⋗
inoremap \verymuchless ⋘
inoremap \ggg ⋙
inoremap \lesseqgtr ⋚
inoremap \gtreqless ⋛
inoremap \eqless ⋜
inoremap \eqgtr ⋝
inoremap \curlyeqprec ⋞
inoremap \curlyeqsucc ⋟
inoremap \npreccurlyeq ⋠
inoremap \nsucccurlyeq ⋡
inoremap \nsqsubseteq ⋢
inoremap \nsqsupseteq ⋣
inoremap \sqsubsetneq ⋤
inoremap \sqspne ⋥
inoremap \lnsim ⋦
inoremap \gnsim ⋧
inoremap \precnsim ⋨
inoremap \succnsim ⋩
inoremap \ntriangleleft ⋪
inoremap \ntriangleright ⋫
inoremap \ntrianglelefteq ⋬
inoremap \ntrianglerighteq ⋭
inoremap \vdots ⋮
inoremap \cdots ⋯
inoremap \adots ⋰
inoremap \ddots ⋱
inoremap \disin ⋲
inoremap \varisins ⋳
inoremap \isins ⋴
inoremap \isindot ⋵
inoremap \varisinobar ⋶
inoremap \isinobar ⋷
inoremap \isinvb ⋸
inoremap \isinE ⋹
inoremap \nisd ⋺
inoremap \varnis ⋻
inoremap \nis ⋼
inoremap \varniobar ⋽
inoremap \niobar ⋾
inoremap \bagmember ⋿
inoremap \diameter ⌀
inoremap \house ⌂
inoremap \varbarwedge ⌅
inoremap \vardoublebarwedge ⌆
inoremap \lceil ⌈
inoremap \rceil ⌉
inoremap \lfloor ⌊
inoremap \rfloor ⌋
inoremap \invnot ⌐
inoremap \sqlozenge ⌑
inoremap \profline ⌒
inoremap \profsurf ⌓
inoremap \recorder ⌕
inoremap \viewdata ⌗
inoremap \turnednot ⌙
inoremap \:watch: ⌚
inoremap \:hourglass: ⌛
inoremap \ulcorner ⌜
inoremap \urcorner ⌝
inoremap \llcorner ⌞
inoremap \lrcorner ⌟
inoremap \frown ⌢
inoremap \smile ⌣
inoremap \varhexagonlrbonds ⌬
inoremap \conictaper ⌲
inoremap \topbot ⌶
inoremap \obar ⌽
inoremap \notslash ⌿
inoremap \notbackslash ⍀
inoremap \boxupcaret ⍓
inoremap \boxquestion ⍰
inoremap \hexagon ⎔
inoremap \dlcorn ⎣
inoremap \lmoustache ⎰
inoremap \rmoustache ⎱
inoremap \overbracket ⎴
inoremap \underbracket ⎵
inoremap \bbrktbrk ⎶
inoremap \sqrtbottom ⎷
inoremap \lvboxline ⎸
inoremap \rvboxline ⎹
inoremap \varcarriagereturn ⏎
inoremap \overbrace ⏞
inoremap \underbrace ⏟
inoremap \trapezium ⏢
inoremap \benzenr ⏣
inoremap \strns ⏤
inoremap \fltns ⏥
inoremap \accurrent ⏦
inoremap \elinters ⏧
inoremap \:fast_forward: ⏩
inoremap \:rewind: ⏪
inoremap \:arrow_double_up: ⏫
inoremap \:arrow_double_down: ⏬
inoremap \:alarm_clock: ⏰
inoremap \:hourglass_flowing_sand: ⏳
inoremap \blanksymbol ␢
inoremap \visiblespace ␣
inoremap \:m: Ⓜ
inoremap \circledS Ⓢ
inoremap \dshfnc ┆
inoremap \sqfnw ┙
inoremap \diagup ╱
inoremap \diagdown ╲
inoremap \blockuphalf ▀
inoremap \blocklowhalf ▄
inoremap \blockfull █
inoremap \blocklefthalf ▌
inoremap \blockrighthalf ▐
inoremap \blockqtrshaded ░
inoremap \blockhalfshaded ▒
inoremap \blockthreeqtrshaded ▓
inoremap \blacksquare ■
inoremap \square □
inoremap \squoval ▢
inoremap \blackinwhitesquare ▣
inoremap \squarehfill ▤
inoremap \squarevfill ▥
inoremap \squarehvfill ▦
inoremap \squarenwsefill ▧
inoremap \squareneswfill ▨
inoremap \squarecrossfill ▩
inoremap \smblksquare ▪
inoremap \smwhtsquare ▫
inoremap \hrectangleblack ▬
inoremap \hrectangle ▭
inoremap \vrectangleblack ▮
inoremap \vrecto ▯
inoremap \parallelogramblack ▰
inoremap \parallelogram ▱
inoremap \bigblacktriangleup ▲
inoremap \bigtriangleup △
inoremap \blacktriangle ▴
inoremap \vartriangle ▵
inoremap \blacktriangleright ▶
inoremap \triangleright ▷
inoremap \smallblacktriangleright ▸
inoremap \smalltriangleright ▹
inoremap \blackpointerright ►
inoremap \whitepointerright ▻
inoremap \bigblacktriangledown ▼
inoremap \bigtriangledown ▽
inoremap \blacktriangledown ▾
inoremap \triangledown ▿
inoremap \blacktriangleleft ◀
inoremap \triangleleft ◁
inoremap \smallblacktriangleleft ◂
inoremap \smalltriangleleft ◃
inoremap \blackpointerleft ◄
inoremap \whitepointerleft ◅
inoremap \mdlgblkdiamond ◆
inoremap \mdlgwhtdiamond ◇
inoremap \blackinwhitediamond ◈
inoremap \fisheye ◉
inoremap \lozenge ◊
inoremap \bigcirc ○
inoremap \dottedcircle ◌
inoremap \circlevertfill ◍
inoremap \bullseye ◎
inoremap \mdlgblkcircle ●
inoremap \cirfl ◐
inoremap \cirfr ◑
inoremap \cirfb ◒
inoremap \circletophalfblack ◓
inoremap \circleurquadblack ◔
inoremap \blackcircleulquadwhite ◕
inoremap \blacklefthalfcircle ◖
inoremap \blackrighthalfcircle ◗
inoremap \rvbull ◘
inoremap \inversewhitecircle ◙
inoremap \invwhiteupperhalfcircle ◚
inoremap \invwhitelowerhalfcircle ◛
inoremap \ularc ◜
inoremap \urarc ◝
inoremap \lrarc ◞
inoremap \llarc ◟
inoremap \topsemicircle ◠
inoremap \botsemicircle ◡
inoremap \lrblacktriangle ◢
inoremap \llblacktriangle ◣
inoremap \ulblacktriangle ◤
inoremap \urblacktriangle ◥
inoremap \smwhtcircle ◦
inoremap \sqfl ◧
inoremap \sqfr ◨
inoremap \squareulblack ◩
inoremap \sqfse ◪
inoremap \boxbar ◫
inoremap \trianglecdot ◬
inoremap \triangleleftblack ◭
inoremap \trianglerightblack ◮
inoremap \lgwhtcircle ◯
inoremap \squareulquad ◰
inoremap \squarellquad ◱
inoremap \squarelrquad ◲
inoremap \squareurquad ◳
inoremap \circleulquad ◴
inoremap \circlellquad ◵
inoremap \circlelrquad ◶
inoremap \circleurquad ◷
inoremap \ultriangle ◸
inoremap \urtriangle ◹
inoremap \lltriangle ◺
inoremap \mdwhtsquare ◻
inoremap \mdblksquare ◼
inoremap \mdsmwhtsquare ◽
inoremap \mdsmblksquare ◾
inoremap \lrtriangle ◿
inoremap \:sunny: ☀
inoremap \:cloud: ☁
inoremap \bigstar ★
inoremap \bigwhitestar ☆
inoremap \astrosun ☉
inoremap \:phone: ☎
inoremap \:ballot_box_with_check: ☑
inoremap \:umbrella_with_rain_drops: ☔
inoremap \:coffee: ☕
inoremap \:point_up: ☝
inoremap \danger ☡
inoremap \:relaxed: ☺
inoremap \blacksmiley ☻
inoremap \sun ☼
inoremap \rightmoon ☽
inoremap \leftmoon ☾
inoremap \mercury ☿
inoremap \female ♀
inoremap \male ♂
inoremap \jupiter ♃
inoremap \saturn ♄
inoremap \uranus ♅
inoremap \neptune ♆
inoremap \pluto ♇
inoremap \aries ♈
inoremap \taurus ♉
inoremap \gemini ♊
inoremap \cancer ♋
inoremap \leo ♌
inoremap \virgo ♍
inoremap \libra ♎
inoremap \scorpio ♏
inoremap \sagittarius ♐
inoremap \capricornus ♑
inoremap \aquarius ♒
inoremap \pisces ♓
inoremap \spadesuit ♠
inoremap \heartsuit ♡
inoremap \diamondsuit ♢
inoremap \clubsuit ♣
inoremap \varspadesuit ♤
inoremap \varheartsuit ♥
inoremap \vardiamondsuit ♦
inoremap \varclubsuit ♧
inoremap \:hotsprings: ♨
inoremap \quarternote ♩
inoremap \eighthnote ♪
inoremap \twonotes ♫
inoremap \flat ♭
inoremap \natural ♮
inoremap \sharp ♯
inoremap \:recycle: ♻
inoremap \acidfree ♾
inoremap \:wheelchair: ♿
inoremap \dicei ⚀
inoremap \diceii ⚁
inoremap \diceiii ⚂
inoremap \diceiv ⚃
inoremap \dicev ⚄
inoremap \dicevi ⚅
inoremap \circledrightdot ⚆
inoremap \circledtwodots ⚇
inoremap \blackcircledrightdot ⚈
inoremap \blackcircledtwodots ⚉
inoremap \:anchor: ⚓
inoremap \:warning: ⚠
inoremap \:zap: ⚡
inoremap \hermaphrodite ⚥
inoremap \mdwhtcircle ⚪
inoremap \mdblkcircle ⚫
inoremap \mdsmwhtcircle ⚬
inoremap \neuter ⚲
inoremap \:soccer: ⚽
inoremap \:baseball: ⚾
inoremap \:snowman: ⛄
inoremap \:partly_sunny: ⛅
inoremap \:ophiuchus: ⛎
inoremap \:no_entry: ⛔
inoremap \:church: ⛪
inoremap \:fountain: ⛲
inoremap \:golf: ⛳
inoremap \:boat: ⛵
inoremap \:tent: ⛺
inoremap \:fuelpump: ⛽
inoremap \:scissors: ✂
inoremap \:white_check_mark: ✅
inoremap \:airplane: ✈
inoremap \:email: ✉
inoremap \:fist: ✊
inoremap \:hand: ✋
inoremap \:v: ✌
inoremap \:pencil2: ✏
inoremap \:black_nib: ✒
inoremap \checkmark ✓
inoremap \:heavy_check_mark: ✔
inoremap \:heavy_multiplication_x: ✖
inoremap \maltese ✠
inoremap \:sparkles: ✨
inoremap \circledstar ✪
inoremap \:eight_spoked_asterisk: ✳
inoremap \:eight_pointed_black_star: ✴
inoremap \varstar ✶
inoremap \dingasterisk ✽
inoremap \:snowflake: ❄
inoremap \:sparkle: ❇
inoremap \:x: ❌
inoremap \:negative_squared_cross_mark: ❎
inoremap \:question: ❓
inoremap \:grey_question: ❔
inoremap \:grey_exclamation: ❕
inoremap \:exclamation: ❗
inoremap \:heart: ❤
inoremap \:heavy_plus_sign: ➕
inoremap \:heavy_minus_sign: ➖
inoremap \:heavy_division_sign: ➗
inoremap \draftingarrow ➛
inoremap \:arrow_right: ➡
inoremap \:curly_loop: ➰
inoremap \:loop: ➿
inoremap \threedangle ⟀
inoremap \whiteinwhitetriangle ⟁
inoremap \perp ⟂
inoremap \bsolhsub ⟈
inoremap \suphsol ⟉
inoremap \wedgedot ⟑
inoremap \upin ⟒
inoremap \leftouterjoin ⟕
inoremap \rightouterjoin ⟖
inoremap \fullouterjoin ⟗
inoremap \bigbot ⟘
inoremap \bigtop ⟙
inoremap \llbracket ⟦
inoremap \rrbracket ⟧
inoremap \langle ⟨
inoremap \rangle ⟩
inoremap \UUparrow ⟰
inoremap \DDownarrow ⟱
inoremap \longleftarrow ⟵
inoremap \longrightarrow ⟶
inoremap \longleftrightarrow ⟷
inoremap \impliedby ⟸
inoremap \implies ⟹
inoremap \Longleftrightarrow ⟺
inoremap \longmapsfrom ⟻
inoremap \longmapsto ⟼
inoremap \Longmapsfrom ⟽
inoremap \Longmapsto ⟾
inoremap \longrightsquigarrow ⟿
inoremap \nvtwoheadrightarrow ⤀
inoremap \nVtwoheadrightarrow ⤁
inoremap \nvLeftarrow ⤂
inoremap \nvRightarrow ⤃
inoremap \nvLeftrightarrow ⤄
inoremap \twoheadmapsto ⤅
inoremap \Mapsfrom ⤆
inoremap \Mapsto ⤇
inoremap \downarrowbarred ⤈
inoremap \uparrowbarred ⤉
inoremap \Uuparrow ⤊
inoremap \Ddownarrow ⤋
inoremap \leftbkarrow ⤌
inoremap \bkarow ⤍
inoremap \leftdbkarrow ⤎
inoremap \dbkarow ⤏
inoremap \drbkarrow ⤐
inoremap \rightdotarrow ⤑
inoremap \UpArrowBar ⤒
inoremap \DownArrowBar ⤓
inoremap \nvrightarrowtail ⤔
inoremap \nVrightarrowtail ⤕
inoremap \twoheadrightarrowtail ⤖
inoremap \nvtwoheadrightarrowtail ⤗
inoremap \nVtwoheadrightarrowtail ⤘
inoremap \diamondleftarrow ⤝
inoremap \rightarrowdiamond ⤞
inoremap \diamondleftarrowbar ⤟
inoremap \barrightarrowdiamond ⤠
inoremap \hksearow ⤥
inoremap \hkswarow ⤦
inoremap \tona ⤧
inoremap \toea ⤨
inoremap \tosa ⤩
inoremap \towa ⤪
inoremap \rdiagovfdiag ⤫
inoremap \fdiagovrdiag ⤬
inoremap \seovnearrow ⤭
inoremap \neovsearrow ⤮
inoremap \fdiagovnearrow ⤯
inoremap \rdiagovsearrow ⤰
inoremap \neovnwarrow ⤱
inoremap \nwovnearrow ⤲
inoremap \:arrow_heading_up: ⤴
inoremap \:arrow_heading_down: ⤵
inoremap \Rlarr ⥂
inoremap \rLarr ⥄
inoremap \rightarrowplus ⥅
inoremap \leftarrowplus ⥆
inoremap \rarrx ⥇
inoremap \leftrightarrowcircle ⥈
inoremap \twoheaduparrowcircle ⥉
inoremap \leftrightharpoonupdown ⥊
inoremap \leftrightharpoondownup ⥋
inoremap \updownharpoonrightleft ⥌
inoremap \updownharpoonleftright ⥍
inoremap \LeftRightVector ⥎
inoremap \RightUpDownVector ⥏
inoremap \DownLeftRightVector ⥐
inoremap \LeftUpDownVector ⥑
inoremap \LeftVectorBar ⥒
inoremap \RightVectorBar ⥓
inoremap \RightUpVectorBar ⥔
inoremap \RightDownVectorBar ⥕
inoremap \DownLeftVectorBar ⥖
inoremap \DownRightVectorBar ⥗
inoremap \LeftUpVectorBar ⥘
inoremap \LeftDownVectorBar ⥙
inoremap \LeftTeeVector ⥚
inoremap \RightTeeVector ⥛
inoremap \RightUpTeeVector ⥜
inoremap \RightDownTeeVector ⥝
inoremap \DownLeftTeeVector ⥞
inoremap \DownRightTeeVector ⥟
inoremap \LeftUpTeeVector ⥠
inoremap \LeftDownTeeVector ⥡
inoremap \leftharpoonsupdown ⥢
inoremap \upharpoonsleftright ⥣
inoremap \rightharpoonsupdown ⥤
inoremap \downharpoonsleftright ⥥
inoremap \leftrightharpoonsup ⥦
inoremap \leftrightharpoonsdown ⥧
inoremap \rightleftharpoonsup ⥨
inoremap \rightleftharpoonsdown ⥩
inoremap \leftharpoonupdash ⥪
inoremap \dashleftharpoondown ⥫
inoremap \rightharpoonupdash ⥬
inoremap \dashrightharpoondown ⥭
inoremap \UpEquilibrium ⥮
inoremap \ReverseUpEquilibrium ⥯
inoremap \RoundImplies ⥰
inoremap \Vvert ⦀
inoremap \Elroang ⦆
inoremap \ddfnc ⦙
inoremap \measuredangleleft ⦛
inoremap \Angle ⦜
inoremap \rightanglemdot ⦝
inoremap \angles ⦞
inoremap \angdnr ⦟
inoremap \lpargt ⦠
inoremap \sphericalangleup ⦡
inoremap \turnangle ⦢
inoremap \revangle ⦣
inoremap \angleubar ⦤
inoremap \revangleubar ⦥
inoremap \wideangledown ⦦
inoremap \wideangleup ⦧
inoremap \measanglerutone ⦨
inoremap \measanglelutonw ⦩
inoremap \measanglerdtose ⦪
inoremap \measangleldtosw ⦫
inoremap \measangleurtone ⦬
inoremap \measangleultonw ⦭
inoremap \measangledrtose ⦮
inoremap \measangledltosw ⦯
inoremap \revemptyset ⦰
inoremap \emptysetobar ⦱
inoremap \emptysetocirc ⦲
inoremap \emptysetoarr ⦳
inoremap \emptysetoarrl ⦴
inoremap \circledparallel ⦷
inoremap \obslash ⦸
inoremap \odotslashdot ⦼
inoremap \circledwhitebullet ⦾
inoremap \circledbullet ⦿
inoremap \olessthan ⧀
inoremap \ogreaterthan ⧁
inoremap \boxdiag ⧄
inoremap \boxbslash ⧅
inoremap \boxast ⧆
inoremap \boxcircle ⧇
inoremap \Lap ⧊
inoremap \defas ⧋
inoremap \LeftTriangleBar ⧏
inoremap \NotLeftTriangleBar ⧏̸
inoremap \RightTriangleBar ⧐
inoremap \NotRightTriangleBar ⧐̸
inoremap \dualmap ⧟
inoremap \lrtriangleeq ⧡
inoremap \shuffle ⧢
inoremap \eparsl ⧣
inoremap \smeparsl ⧤
inoremap \eqvparsl ⧥
inoremap \blacklozenge ⧫
inoremap \RuleDelayed ⧴
inoremap \dsol ⧶
inoremap \rsolbar ⧷
inoremap \doubleplus ⧺
inoremap \tripleplus ⧻
inoremap \bigodot ⨀
inoremap \bigoplus ⨁
inoremap \bigotimes ⨂
inoremap \bigcupdot ⨃
inoremap \biguplus ⨄
inoremap \bigsqcap ⨅
inoremap \bigsqcup ⨆
inoremap \conjquant ⨇
inoremap \disjquant ⨈
inoremap \bigtimes ⨉
inoremap \modtwosum ⨊
inoremap \sumint ⨋
inoremap \iiiint ⨌
inoremap \intbar ⨍
inoremap \intBar ⨎
inoremap \clockoint ⨏
inoremap \cirfnint ⨐
inoremap \awint ⨑
inoremap \rppolint ⨒
inoremap \scpolint ⨓
inoremap \npolint ⨔
inoremap \pointint ⨕
inoremap \sqrint ⨖
inoremap \intx ⨘
inoremap \intcap ⨙
inoremap \intcup ⨚
inoremap \upint ⨛
inoremap \lowint ⨜
inoremap \join ⨝
inoremap \bbsemi ⨟
inoremap \ringplus ⨢
inoremap \plushat ⨣
inoremap \simplus ⨤
inoremap \plusdot ⨥
inoremap \plussim ⨦
inoremap \plussubtwo ⨧
inoremap \plustrif ⨨
inoremap \commaminus ⨩
inoremap \minusdot ⨪
inoremap \minusfdots ⨫
inoremap \minusrdots ⨬
inoremap \opluslhrim ⨭
inoremap \oplusrhrim ⨮
inoremap \Times ⨯
inoremap \dottimes ⨰
inoremap \timesbar ⨱
inoremap \btimes ⨲
inoremap \smashtimes ⨳
inoremap \otimeslhrim ⨴
inoremap \otimesrhrim ⨵
inoremap \otimeshat ⨶
inoremap \Otimes ⨷
inoremap \odiv ⨸
inoremap \triangleplus ⨹
inoremap \triangleminus ⨺
inoremap \triangletimes ⨻
inoremap \intprod ⨼
inoremap \intprodr ⨽
inoremap \amalg ⨿
inoremap \capdot ⩀
inoremap \uminus ⩁
inoremap \barcup ⩂
inoremap \barcap ⩃
inoremap \capwedge ⩄
inoremap \cupvee ⩅
inoremap \twocups ⩊
inoremap \twocaps ⩋
inoremap \closedvarcup ⩌
inoremap \closedvarcap ⩍
inoremap \Sqcap ⩎
inoremap \Sqcup ⩏
inoremap \closedvarcupsmashprod ⩐
inoremap \wedgeodot ⩑
inoremap \veeodot ⩒
inoremap \And ⩓
inoremap \Or ⩔
inoremap \wedgeonwedge ⩕
inoremap \ElOr ⩖
inoremap \bigslopedvee ⩗
inoremap \bigslopedwedge ⩘
inoremap \wedgemidvert ⩚
inoremap \veemidvert ⩛
inoremap \midbarwedge ⩜
inoremap \midbarvee ⩝
inoremap \perspcorrespond ⩞
inoremap \minhat ⩟
inoremap \wedgedoublebar ⩠
inoremap \varveebar ⩡
inoremap \doublebarvee ⩢
inoremap \veedoublebar ⩣
inoremap \eqdot ⩦
inoremap \dotequiv ⩧
inoremap \dotsim ⩪
inoremap \simrdots ⩫
inoremap \simminussim ⩬
inoremap \congdot ⩭
inoremap \asteq ⩮
inoremap \hatapprox ⩯
inoremap \approxeqq ⩰
inoremap \eqqplus ⩱
inoremap \pluseqq ⩲
inoremap \eqqsim ⩳
inoremap \Coloneq ⩴
inoremap \Equal ⩵
inoremap \eqeqeq ⩶
inoremap \ddotseq ⩷
inoremap \equivDD ⩸
inoremap \ltcir ⩹
inoremap \gtcir ⩺
inoremap \ltquest ⩻
inoremap \gtquest ⩼
inoremap \leqslant ⩽
inoremap \nleqslant ⩽̸
inoremap \geqslant ⩾
inoremap \ngeqslant ⩾̸
inoremap \lesdot ⩿
inoremap \gesdot ⪀
inoremap \lesdoto ⪁
inoremap \gesdoto ⪂
inoremap \lesdotor ⪃
inoremap \gesdotol ⪄
inoremap \lessapprox ⪅
inoremap \gtrapprox ⪆
inoremap \lneq ⪇
inoremap \gneq ⪈
inoremap \lnapprox ⪉
inoremap \gnapprox ⪊
inoremap \lesseqqgtr ⪋
inoremap \gtreqqless ⪌
inoremap \lsime ⪍
inoremap \gsime ⪎
inoremap \lsimg ⪏
inoremap \gsiml ⪐
inoremap \lgE ⪑
inoremap \glE ⪒
inoremap \lesges ⪓
inoremap \gesles ⪔
inoremap \eqslantless ⪕
inoremap \eqslantgtr ⪖
inoremap \elsdot ⪗
inoremap \egsdot ⪘
inoremap \eqqless ⪙
inoremap \eqqgtr ⪚
inoremap \eqqslantless ⪛
inoremap \eqqslantgtr ⪜
inoremap \simless ⪝
inoremap \simgtr ⪞
inoremap \simlE ⪟
inoremap \simgE ⪠
inoremap \NestedLessLess ⪡
inoremap \NotNestedLessLess ⪡̸
inoremap \NestedGreaterGreater ⪢
inoremap \NotNestedGreaterGreater ⪢̸
inoremap \partialmeetcontraction ⪣
inoremap \glj ⪤
inoremap \gla ⪥
inoremap \ltcc ⪦
inoremap \gtcc ⪧
inoremap \lescc ⪨
inoremap \gescc ⪩
inoremap \smt ⪪
inoremap \lat ⪫
inoremap \smte ⪬
inoremap \late ⪭
inoremap \bumpeqq ⪮
inoremap \preceq ⪯
inoremap \npreceq ⪯̸
inoremap \succeq ⪰
inoremap \nsucceq ⪰̸
inoremap \precneq ⪱
inoremap \succneq ⪲
inoremap \preceqq ⪳
inoremap \succeqq ⪴
inoremap \precneqq ⪵
inoremap \succneqq ⪶
inoremap \precapprox ⪷
inoremap \succapprox ⪸
inoremap \precnapprox ⪹
inoremap \succnapprox ⪺
inoremap \Prec ⪻
inoremap \Succ ⪼
inoremap \subsetdot ⪽
inoremap \supsetdot ⪾
inoremap \subsetplus ⪿
inoremap \supsetplus ⫀
inoremap \submult ⫁
inoremap \supmult ⫂
inoremap \subedot ⫃
inoremap \supedot ⫄
inoremap \subseteqq ⫅
inoremap \nsubseteqq ⫅̸
inoremap \supseteqq ⫆
inoremap \nsupseteqq ⫆̸
inoremap \subsim ⫇
inoremap \supsim ⫈
inoremap \subsetapprox ⫉
inoremap \supsetapprox ⫊
inoremap \subsetneqq ⫋
inoremap \supsetneqq ⫌
inoremap \lsqhook ⫍
inoremap \rsqhook ⫎
inoremap \csub ⫏
inoremap \csup ⫐
inoremap \csube ⫑
inoremap \csupe ⫒
inoremap \subsup ⫓
inoremap \supsub ⫔
inoremap \subsub ⫕
inoremap \supsup ⫖
inoremap \suphsub ⫗
inoremap \supdsub ⫘
inoremap \forkv ⫙
inoremap \mlcp ⫛
inoremap \forks ⫝̸
inoremap \forksnot ⫝
inoremap \dashV ⫣
inoremap \Dashv ⫤
inoremap \Top ⫪
inoremap \upvDash \indep ⫫
inoremap \interleave ⫴
inoremap \tdcol ⫶
inoremap \lllnest ⫷
inoremap \gggnest ⫸
inoremap \leqqslant ⫹
inoremap \geqqslant ⫺
inoremap \:arrow_left: ⬅
inoremap \:arrow_up: ⬆
inoremap \:arrow_down: ⬇
inoremap \squaretopblack ⬒
inoremap \squarebotblack ⬓
inoremap \squareurblack ⬔
inoremap \squarellblack ⬕
inoremap \diamondleftblack ⬖
inoremap \diamondrightblack ⬗
inoremap \diamondtopblack ⬘
inoremap \diamondbotblack ⬙
inoremap \dottedsquare ⬚
inoremap \lgblksquare ⬛
inoremap \lgwhtsquare ⬜
inoremap \vysmblksquare ⬝
inoremap \vysmwhtsquare ⬞
inoremap \pentagonblack ⬟
inoremap \pentagon ⬠
inoremap \varhexagon ⬡
inoremap \varhexagonblack ⬢
inoremap \hexagonblack ⬣
inoremap \lgblkcircle ⬤
inoremap \mdblkdiamond ⬥
inoremap \mdwhtdiamond ⬦
inoremap \mdblklozenge ⬧
inoremap \mdwhtlozenge ⬨
inoremap \smblkdiamond ⬩
inoremap \smblklozenge ⬪
inoremap \smwhtlozenge ⬫
inoremap \blkhorzoval ⬬
inoremap \whthorzoval ⬭
inoremap \blkvertoval ⬮
inoremap \whtvertoval ⬯
inoremap \circleonleftarrow ⬰
inoremap \leftthreearrows ⬱
inoremap \leftarrowonoplus ⬲
inoremap \longleftsquigarrow ⬳
inoremap \nvtwoheadleftarrow ⬴
inoremap \nVtwoheadleftarrow ⬵
inoremap \twoheadmapsfrom ⬶
inoremap \twoheadleftdbkarrow ⬷
inoremap \leftdotarrow ⬸
inoremap \nvleftarrowtail ⬹
inoremap \nVleftarrowtail ⬺
inoremap \twoheadleftarrowtail ⬻
inoremap \nvtwoheadleftarrowtail ⬼
inoremap \nVtwoheadleftarrowtail ⬽
inoremap \leftarrowx ⬾
inoremap \leftcurvedarrow ⬿
inoremap \equalleftarrow ⭀
inoremap \bsimilarleftarrow ⭁
inoremap \leftarrowbackapprox ⭂
inoremap \rightarrowgtr ⭃
inoremap \rightarrowsupset ⭄
inoremap \LLeftarrow ⭅
inoremap \RRightarrow ⭆
inoremap \bsimilarrightarrow ⭇
inoremap \rightarrowbackapprox ⭈
inoremap \similarleftarrow ⭉
inoremap \leftarrowapprox ⭊
inoremap \leftarrowbsimilar ⭋
inoremap \rightarrowbsimilar ⭌
inoremap \medwhitestar ⭐
inoremap \medblackstar ⭑
inoremap \smwhitestar ⭒
inoremap \rightpentagonblack ⭓
inoremap \rightpentagon ⭔
inoremap \:o: ⭕
inoremap \_j ⱼ
inoremap \^V ⱽ
inoremap \postalmark 〒
inoremap \:wavy_dash: 〰
inoremap \:part_alternation_mark: 〽
inoremap \:congratulations: ㊗
inoremap \:secret: ㊙
inoremap \^uparrow ꜛ
inoremap \^downarrow ꜜ
inoremap \^! ꜝ
inoremap \bfA 𝐀
inoremap \bfB 𝐁
inoremap \bfC 𝐂
inoremap \bfD 𝐃
inoremap \bfE 𝐄
inoremap \bfF 𝐅
inoremap \bfG 𝐆
inoremap \bfH 𝐇
inoremap \bfI 𝐈
inoremap \bfJ 𝐉
inoremap \bfK 𝐊
inoremap \bfL 𝐋
inoremap \bfM 𝐌
inoremap \bfN 𝐍
inoremap \bfO 𝐎
inoremap \bfP 𝐏
inoremap \bfQ 𝐐
inoremap \bfR 𝐑
inoremap \bfS 𝐒
inoremap \bfT 𝐓
inoremap \bfU 𝐔
inoremap \bfV 𝐕
inoremap \bfW 𝐖
inoremap \bfX 𝐗
inoremap \bfY 𝐘
inoremap \bfZ 𝐙
inoremap \bfa 𝐚
inoremap \bfb 𝐛
inoremap \bfc 𝐜
inoremap \bfd 𝐝
inoremap \bfe 𝐞
inoremap \bff 𝐟
inoremap \bfg 𝐠
inoremap \bfh 𝐡
inoremap \bfi 𝐢
inoremap \bfj 𝐣
inoremap \bfk 𝐤
inoremap \bfl 𝐥
inoremap \bfm 𝐦
inoremap \bfn 𝐧
inoremap \bfo 𝐨
inoremap \bfp 𝐩
inoremap \bfq 𝐪
inoremap \bfr 𝐫
inoremap \bfs 𝐬
inoremap \bft 𝐭
inoremap \bfu 𝐮
inoremap \bfv 𝐯
inoremap \bfw 𝐰
inoremap \bfx 𝐱
inoremap \bfy 𝐲
inoremap \bfz 𝐳
inoremap \itA 𝐴
inoremap \itB 𝐵
inoremap \itC 𝐶
inoremap \itD 𝐷
inoremap \itE 𝐸
inoremap \itF 𝐹
inoremap \itG 𝐺
inoremap \itH 𝐻
inoremap \itI 𝐼
inoremap \itJ 𝐽
inoremap \itK 𝐾
inoremap \itL 𝐿
inoremap \itM 𝑀
inoremap \itN 𝑁
inoremap \itO 𝑂
inoremap \itP 𝑃
inoremap \itQ 𝑄
inoremap \itR 𝑅
inoremap \itS 𝑆
inoremap \itT 𝑇
inoremap \itU 𝑈
inoremap \itV 𝑉
inoremap \itW 𝑊
inoremap \itX 𝑋
inoremap \itY 𝑌
inoremap \itZ 𝑍
inoremap \ita 𝑎
inoremap \itb 𝑏
inoremap \itc 𝑐
inoremap \itd 𝑑
inoremap \ite 𝑒
inoremap \itf 𝑓
inoremap \itg 𝑔
inoremap \iti 𝑖
inoremap \itj 𝑗
inoremap \itk 𝑘
inoremap \itl 𝑙
inoremap \itm 𝑚
inoremap \itn 𝑛
inoremap \ito 𝑜
inoremap \itp 𝑝
inoremap \itq 𝑞
inoremap \itr 𝑟
inoremap \its 𝑠
inoremap \itt 𝑡
inoremap \itu 𝑢
inoremap \itv 𝑣
inoremap \itw 𝑤
inoremap \itx 𝑥
inoremap \ity 𝑦
inoremap \itz 𝑧
inoremap \biA 𝑨
inoremap \biB 𝑩
inoremap \biC 𝑪
inoremap \biD 𝑫
inoremap \biE 𝑬
inoremap \biF 𝑭
inoremap \biG 𝑮
inoremap \biH 𝑯
inoremap \biI 𝑰
inoremap \biJ 𝑱
inoremap \biK 𝑲
inoremap \biL 𝑳
inoremap \biM 𝑴
inoremap \biN 𝑵
inoremap \biO 𝑶
inoremap \biP 𝑷
inoremap \biQ 𝑸
inoremap \biR 𝑹
inoremap \biS 𝑺
inoremap \biT 𝑻
inoremap \biU 𝑼
inoremap \biV 𝑽
inoremap \biW 𝑾
inoremap \biX 𝑿
inoremap \biY 𝒀
inoremap \biZ 𝒁
inoremap \bia 𝒂
inoremap \bib 𝒃
inoremap \bic 𝒄
inoremap \bid 𝒅
inoremap \bie 𝒆
inoremap \bif 𝒇
inoremap \big 𝒈
inoremap \bih 𝒉
inoremap \bii 𝒊
inoremap \bij 𝒋
inoremap \bik 𝒌
inoremap \bil 𝒍
inoremap \bim 𝒎
inoremap \bin 𝒏
inoremap \bio 𝒐
inoremap \bip 𝒑
inoremap \biq 𝒒
inoremap \bir 𝒓
inoremap \bis 𝒔
inoremap \bit 𝒕
inoremap \biu 𝒖
inoremap \biv 𝒗
inoremap \biw 𝒘
inoremap \bix 𝒙
inoremap \biy 𝒚
inoremap \biz 𝒛
inoremap \scrA 𝒜
inoremap \scrC 𝒞
inoremap \scrD 𝒟
inoremap \scrG 𝒢
inoremap \scrJ 𝒥
inoremap \scrK 𝒦
inoremap \scrN 𝒩
inoremap \scrO 𝒪
inoremap \scrP 𝒫
inoremap \scrQ 𝒬
inoremap \scrS 𝒮
inoremap \scrT 𝒯
inoremap \scrU 𝒰
inoremap \scrV 𝒱
inoremap \scrW 𝒲
inoremap \scrX 𝒳
inoremap \scrY 𝒴
inoremap \scrZ 𝒵
inoremap \scra 𝒶
inoremap \scrb 𝒷
inoremap \scrc 𝒸
inoremap \scrd 𝒹
inoremap \scrf 𝒻
inoremap \scrh 𝒽
inoremap \scri 𝒾
inoremap \scrj 𝒿
inoremap \scrk 𝓀
inoremap \scrl 𝓁
inoremap \scrm 𝓂
inoremap \scrn 𝓃
inoremap \scrp 𝓅
inoremap \scrq 𝓆
inoremap \scrr 𝓇
inoremap \scrs 𝓈
inoremap \scrt 𝓉
inoremap \scru 𝓊
inoremap \scrv 𝓋
inoremap \scrw 𝓌
inoremap \scrx 𝓍
inoremap \scry 𝓎
inoremap \scrz 𝓏
inoremap \bscrA 𝓐
inoremap \bscrB 𝓑
inoremap \bscrC 𝓒
inoremap \bscrD 𝓓
inoremap \bscrE 𝓔
inoremap \bscrF 𝓕
inoremap \bscrG 𝓖
inoremap \bscrH 𝓗
inoremap \bscrI 𝓘
inoremap \bscrJ 𝓙
inoremap \bscrK 𝓚
inoremap \bscrL 𝓛
inoremap \bscrM 𝓜
inoremap \bscrN 𝓝
inoremap \bscrO 𝓞
inoremap \bscrP 𝓟
inoremap \bscrQ 𝓠
inoremap \bscrR 𝓡
inoremap \bscrS 𝓢
inoremap \bscrT 𝓣
inoremap \bscrU 𝓤
inoremap \bscrV 𝓥
inoremap \bscrW 𝓦
inoremap \bscrX 𝓧
inoremap \bscrY 𝓨
inoremap \bscrZ 𝓩
inoremap \bscra 𝓪
inoremap \bscrb 𝓫
inoremap \bscrc 𝓬
inoremap \bscrd 𝓭
inoremap \bscre 𝓮
inoremap \bscrf 𝓯
inoremap \bscrg 𝓰
inoremap \bscrh 𝓱
inoremap \bscri 𝓲
inoremap \bscrj 𝓳
inoremap \bscrk 𝓴
inoremap \bscrl 𝓵
inoremap \bscrm 𝓶
inoremap \bscrn 𝓷
inoremap \bscro 𝓸
inoremap \bscrp 𝓹
inoremap \bscrq 𝓺
inoremap \bscrr 𝓻
inoremap \bscrs 𝓼
inoremap \bscrt 𝓽
inoremap \bscru 𝓾
inoremap \bscrv 𝓿
inoremap \bscrw 𝔀
inoremap \bscrx 𝔁
inoremap \bscry 𝔂
inoremap \bscrz 𝔃
inoremap \frakA 𝔄
inoremap \frakB 𝔅
inoremap \frakD 𝔇
inoremap \frakE 𝔈
inoremap \frakF 𝔉
inoremap \frakG 𝔊
inoremap \frakJ 𝔍
inoremap \frakK 𝔎
inoremap \frakL 𝔏
inoremap \frakM 𝔐
inoremap \frakN 𝔑
inoremap \frakO 𝔒
inoremap \frakP 𝔓
inoremap \frakQ 𝔔
inoremap \frakS 𝔖
inoremap \frakT 𝔗
inoremap \frakU 𝔘
inoremap \frakV 𝔙
inoremap \frakW 𝔚
inoremap \frakX 𝔛
inoremap \frakY 𝔜
inoremap \fraka 𝔞
inoremap \frakb 𝔟
inoremap \frakc 𝔠
inoremap \frakd 𝔡
inoremap \frake 𝔢
inoremap \frakf 𝔣
inoremap \frakg 𝔤
inoremap \frakh 𝔥
inoremap \fraki 𝔦
inoremap \frakj 𝔧
inoremap \frakk 𝔨
inoremap \frakl 𝔩
inoremap \frakm 𝔪
inoremap \frakn 𝔫
inoremap \frako 𝔬
inoremap \frakp 𝔭
inoremap \frakq 𝔮
inoremap \frakr 𝔯
inoremap \fraks 𝔰
inoremap \frakt 𝔱
inoremap \fraku 𝔲
inoremap \frakv 𝔳
inoremap \frakw 𝔴
inoremap \frakx 𝔵
inoremap \fraky 𝔶
inoremap \frakz 𝔷
inoremap \bbA 𝔸
inoremap \bbB 𝔹
inoremap \bbD 𝔻
inoremap \bbE 𝔼
inoremap \bbF 𝔽
inoremap \bbG 𝔾
inoremap \bbI 𝕀
inoremap \bbJ 𝕁
inoremap \bbK 𝕂
inoremap \bbL 𝕃
inoremap \bbM 𝕄
inoremap \bbO 𝕆
inoremap \bbS 𝕊
inoremap \bbT 𝕋
inoremap \bbU 𝕌
inoremap \bbV 𝕍
inoremap \bbW 𝕎
inoremap \bbX 𝕏
inoremap \bbY 𝕐
inoremap \bba 𝕒
inoremap \bbb 𝕓
inoremap \bbc 𝕔
inoremap \bbd 𝕕
inoremap \bbe 𝕖
inoremap \bbf 𝕗
inoremap \bbg 𝕘
inoremap \bbh 𝕙
inoremap \bbi 𝕚
inoremap \bbj 𝕛
inoremap \bbk 𝕜
inoremap \bbl 𝕝
inoremap \bbm 𝕞
inoremap \bbn 𝕟
inoremap \bbo 𝕠
inoremap \bbp 𝕡
inoremap \bbq 𝕢
inoremap \bbr 𝕣
inoremap \bbs 𝕤
inoremap \bbt 𝕥
inoremap \bbu 𝕦
inoremap \bbv 𝕧
inoremap \bbw 𝕨
inoremap \bbx 𝕩
inoremap \bby 𝕪
inoremap \bbz 𝕫
inoremap \bfrakA 𝕬
inoremap \bfrakB 𝕭
inoremap \bfrakC 𝕮
inoremap \bfrakD 𝕯
inoremap \bfrakE 𝕰
inoremap \bfrakF 𝕱
inoremap \bfrakG 𝕲
inoremap \bfrakH 𝕳
inoremap \bfrakI 𝕴
inoremap \bfrakJ 𝕵
inoremap \bfrakK 𝕶
inoremap \bfrakL 𝕷
inoremap \bfrakM 𝕸
inoremap \bfrakN 𝕹
inoremap \bfrakO 𝕺
inoremap \bfrakP 𝕻
inoremap \bfrakQ 𝕼
inoremap \bfrakR 𝕽
inoremap \bfrakS 𝕾
inoremap \bfrakT 𝕿
inoremap \bfrakU 𝖀
inoremap \bfrakV 𝖁
inoremap \bfrakW 𝖂
inoremap \bfrakX 𝖃
inoremap \bfrakY 𝖄
inoremap \bfrakZ 𝖅
inoremap \bfraka 𝖆
inoremap \bfrakb 𝖇
inoremap \bfrakc 𝖈
inoremap \bfrakd 𝖉
inoremap \bfrake 𝖊
inoremap \bfrakf 𝖋
inoremap \bfrakg 𝖌
inoremap \bfrakh 𝖍
inoremap \bfraki 𝖎
inoremap \bfrakj 𝖏
inoremap \bfrakk 𝖐
inoremap \bfrakl 𝖑
inoremap \bfrakm 𝖒
inoremap \bfrakn 𝖓
inoremap \bfrako 𝖔
inoremap \bfrakp 𝖕
inoremap \bfrakq 𝖖
inoremap \bfrakr 𝖗
inoremap \bfraks 𝖘
inoremap \bfrakt 𝖙
inoremap \bfraku 𝖚
inoremap \bfrakv 𝖛
inoremap \bfrakw 𝖜
inoremap \bfrakx 𝖝
inoremap \bfraky 𝖞
inoremap \bfrakz 𝖟
inoremap \sansA 𝖠
inoremap \sansB 𝖡
inoremap \sansC 𝖢
inoremap \sansD 𝖣
inoremap \sansE 𝖤
inoremap \sansF 𝖥
inoremap \sansG 𝖦
inoremap \sansH 𝖧
inoremap \sansI 𝖨
inoremap \sansJ 𝖩
inoremap \sansK 𝖪
inoremap \sansL 𝖫
inoremap \sansM 𝖬
inoremap \sansN 𝖭
inoremap \sansO 𝖮
inoremap \sansP 𝖯
inoremap \sansQ 𝖰
inoremap \sansR 𝖱
inoremap \sansS 𝖲
inoremap \sansT 𝖳
inoremap \sansU 𝖴
inoremap \sansV 𝖵
inoremap \sansW 𝖶
inoremap \sansX 𝖷
inoremap \sansY 𝖸
inoremap \sansZ 𝖹
inoremap \sansa 𝖺
inoremap \sansb 𝖻
inoremap \sansc 𝖼
inoremap \sansd 𝖽
inoremap \sanse 𝖾
inoremap \sansf 𝖿
inoremap \sansg 𝗀
inoremap \sansh 𝗁
inoremap \sansi 𝗂
inoremap \sansj 𝗃
inoremap \sansk 𝗄
inoremap \sansl 𝗅
inoremap \sansm 𝗆
inoremap \sansn 𝗇
inoremap \sanso 𝗈
inoremap \sansp 𝗉
inoremap \sansq 𝗊
inoremap \sansr 𝗋
inoremap \sanss 𝗌
inoremap \sanst 𝗍
inoremap \sansu 𝗎
inoremap \sansv 𝗏
inoremap \sansw 𝗐
inoremap \sansx 𝗑
inoremap \sansy 𝗒
inoremap \sansz 𝗓
inoremap \bsansA 𝗔
inoremap \bsansB 𝗕
inoremap \bsansC 𝗖
inoremap \bsansD 𝗗
inoremap \bsansE 𝗘
inoremap \bsansF 𝗙
inoremap \bsansG 𝗚
inoremap \bsansH 𝗛
inoremap \bsansI 𝗜
inoremap \bsansJ 𝗝
inoremap \bsansK 𝗞
inoremap \bsansL 𝗟
inoremap \bsansM 𝗠
inoremap \bsansN 𝗡
inoremap \bsansO 𝗢
inoremap \bsansP 𝗣
inoremap \bsansQ 𝗤
inoremap \bsansR 𝗥
inoremap \bsansS 𝗦
inoremap \bsansT 𝗧
inoremap \bsansU 𝗨
inoremap \bsansV 𝗩
inoremap \bsansW 𝗪
inoremap \bsansX 𝗫
inoremap \bsansY 𝗬
inoremap \bsansZ 𝗭
inoremap \bsansa 𝗮
inoremap \bsansb 𝗯
inoremap \bsansc 𝗰
inoremap \bsansd 𝗱
inoremap \bsanse 𝗲
inoremap \bsansf 𝗳
inoremap \bsansg 𝗴
inoremap \bsansh 𝗵
inoremap \bsansi 𝗶
inoremap \bsansj 𝗷
inoremap \bsansk 𝗸
inoremap \bsansl 𝗹
inoremap \bsansm 𝗺
inoremap \bsansn 𝗻
inoremap \bsanso 𝗼
inoremap \bsansp 𝗽
inoremap \bsansq 𝗾
inoremap \bsansr 𝗿
inoremap \bsanss 𝘀
inoremap \bsanst 𝘁
inoremap \bsansu 𝘂
inoremap \bsansv 𝘃
inoremap \bsansw 𝘄
inoremap \bsansx 𝘅
inoremap \bsansy 𝘆
inoremap \bsansz 𝘇
inoremap \isansA 𝘈
inoremap \isansB 𝘉
inoremap \isansC 𝘊
inoremap \isansD 𝘋
inoremap \isansE 𝘌
inoremap \isansF 𝘍
inoremap \isansG 𝘎
inoremap \isansH 𝘏
inoremap \isansI 𝘐
inoremap \isansJ 𝘑
inoremap \isansK 𝘒
inoremap \isansL 𝘓
inoremap \isansM 𝘔
inoremap \isansN 𝘕
inoremap \isansO 𝘖
inoremap \isansP 𝘗
inoremap \isansQ 𝘘
inoremap \isansR 𝘙
inoremap \isansS 𝘚
inoremap \isansT 𝘛
inoremap \isansU 𝘜
inoremap \isansV 𝘝
inoremap \isansW 𝘞
inoremap \isansX 𝘟
inoremap \isansY 𝘠
inoremap \isansZ 𝘡
inoremap \isansa 𝘢
inoremap \isansb 𝘣
inoremap \isansc 𝘤
inoremap \isansd 𝘥
inoremap \isanse 𝘦
inoremap \isansf 𝘧
inoremap \isansg 𝘨
inoremap \isansh 𝘩
inoremap \isansi 𝘪
inoremap \isansj 𝘫
inoremap \isansk 𝘬
inoremap \isansl 𝘭
inoremap \isansm 𝘮
inoremap \isansn 𝘯
inoremap \isanso 𝘰
inoremap \isansp 𝘱
inoremap \isansq 𝘲
inoremap \isansr 𝘳
inoremap \isanss 𝘴
inoremap \isanst 𝘵
inoremap \isansu 𝘶
inoremap \isansv 𝘷
inoremap \isansw 𝘸
inoremap \isansx 𝘹
inoremap \isansy 𝘺
inoremap \isansz 𝘻
inoremap \bisansA 𝘼
inoremap \bisansB 𝘽
inoremap \bisansC 𝘾
inoremap \bisansD 𝘿
inoremap \bisansE 𝙀
inoremap \bisansF 𝙁
inoremap \bisansG 𝙂
inoremap \bisansH 𝙃
inoremap \bisansI 𝙄
inoremap \bisansJ 𝙅
inoremap \bisansK 𝙆
inoremap \bisansL 𝙇
inoremap \bisansM 𝙈
inoremap \bisansN 𝙉
inoremap \bisansO 𝙊
inoremap \bisansP 𝙋
inoremap \bisansQ 𝙌
inoremap \bisansR 𝙍
inoremap \bisansS 𝙎
inoremap \bisansT 𝙏
inoremap \bisansU 𝙐
inoremap \bisansV 𝙑
inoremap \bisansW 𝙒
inoremap \bisansX 𝙓
inoremap \bisansY 𝙔
inoremap \bisansZ 𝙕
inoremap \bisansa 𝙖
inoremap \bisansb 𝙗
inoremap \bisansc 𝙘
inoremap \bisansd 𝙙
inoremap \bisanse 𝙚
inoremap \bisansf 𝙛
inoremap \bisansg 𝙜
inoremap \bisansh 𝙝
inoremap \bisansi 𝙞
inoremap \bisansj 𝙟
inoremap \bisansk 𝙠
inoremap \bisansl 𝙡
inoremap \bisansm 𝙢
inoremap \bisansn 𝙣
inoremap \bisanso 𝙤
inoremap \bisansp 𝙥
inoremap \bisansq 𝙦
inoremap \bisansr 𝙧
inoremap \bisanss 𝙨
inoremap \bisanst 𝙩
inoremap \bisansu 𝙪
inoremap \bisansv 𝙫
inoremap \bisansw 𝙬
inoremap \bisansx 𝙭
inoremap \bisansy 𝙮
inoremap \bisansz 𝙯
inoremap \ttA 𝙰
inoremap \ttB 𝙱
inoremap \ttC 𝙲
inoremap \ttD 𝙳
inoremap \ttE 𝙴
inoremap \ttF 𝙵
inoremap \ttG 𝙶
inoremap \ttH 𝙷
inoremap \ttI 𝙸
inoremap \ttJ 𝙹
inoremap \ttK 𝙺
inoremap \ttL 𝙻
inoremap \ttM 𝙼
inoremap \ttN 𝙽
inoremap \ttO 𝙾
inoremap \ttP 𝙿
inoremap \ttQ 𝚀
inoremap \ttR 𝚁
inoremap \ttS 𝚂
inoremap \ttT 𝚃
inoremap \ttU 𝚄
inoremap \ttV 𝚅
inoremap \ttW 𝚆
inoremap \ttX 𝚇
inoremap \ttY 𝚈
inoremap \ttZ 𝚉
inoremap \tta 𝚊
inoremap \ttb 𝚋
inoremap \ttc 𝚌
inoremap \ttd 𝚍
inoremap \tte 𝚎
inoremap \ttf 𝚏
inoremap \ttg 𝚐
inoremap \tth 𝚑
inoremap \tti 𝚒
inoremap \ttj 𝚓
inoremap \ttk 𝚔
inoremap \ttl 𝚕
inoremap \ttm 𝚖
inoremap \ttn 𝚗
inoremap \tto 𝚘
inoremap \ttp 𝚙
inoremap \ttq 𝚚
inoremap \ttr 𝚛
inoremap \tts 𝚜
inoremap \ttt 𝚝
inoremap \ttu 𝚞
inoremap \ttv 𝚟
inoremap \ttw 𝚠
inoremap \ttx 𝚡
inoremap \tty 𝚢
inoremap \ttz 𝚣
inoremap \itimath 𝚤
inoremap \itjmath 𝚥
inoremap \bfAlpha 𝚨
inoremap \bfBeta 𝚩
inoremap \bfGamma 𝚪
inoremap \bfDelta 𝚫
inoremap \bfEpsilon 𝚬
inoremap \bfZeta 𝚭
inoremap \bfEta 𝚮
inoremap \bfTheta 𝚯
inoremap \bfIota 𝚰
inoremap \bfKappa 𝚱
inoremap \bfLambda 𝚲
inoremap \bfMu 𝚳
inoremap \bfNu 𝚴
inoremap \bfXi 𝚵
inoremap \bfOmicron 𝚶
inoremap \bfPi 𝚷
inoremap \bfRho 𝚸
inoremap \bfvarTheta 𝚹
inoremap \bfSigma 𝚺
inoremap \bfTau 𝚻
inoremap \bfUpsilon 𝚼
inoremap \bfPhi 𝚽
inoremap \bfChi 𝚾
inoremap \bfPsi 𝚿
inoremap \bfOmega 𝛀
inoremap \bfnabla 𝛁
inoremap \bfalpha 𝛂
inoremap \bfbeta 𝛃
inoremap \bfgamma 𝛄
inoremap \bfdelta 𝛅
inoremap \bfvarepsilon 𝛆
inoremap \bfzeta 𝛇
inoremap \bfeta 𝛈
inoremap \bftheta 𝛉
inoremap \bfiota 𝛊
inoremap \bfkappa 𝛋
inoremap \bflambda 𝛌
inoremap \bfmu 𝛍
inoremap \bfnu 𝛎
inoremap \bfxi 𝛏
inoremap \bfomicron 𝛐
inoremap \bfpi 𝛑
inoremap \bfrho 𝛒
inoremap \bfvarsigma 𝛓
inoremap \bfsigma 𝛔
inoremap \bftau 𝛕
inoremap \bfupsilon 𝛖
inoremap \bfvarphi 𝛗
inoremap \bfchi 𝛘
inoremap \bfpsi 𝛙
inoremap \bfomega 𝛚
inoremap \bfpartial 𝛛
inoremap \bfepsilon 𝛜
inoremap \bfvartheta 𝛝
inoremap \bfvarkappa 𝛞
inoremap \bfphi 𝛟
inoremap \bfvarrho 𝛠
inoremap \bfvarpi 𝛡
inoremap \itAlpha 𝛢
inoremap \itBeta 𝛣
inoremap \itGamma 𝛤
inoremap \itDelta 𝛥
inoremap \itEpsilon 𝛦
inoremap \itZeta 𝛧
inoremap \itEta 𝛨
inoremap \itTheta 𝛩
inoremap \itIota 𝛪
inoremap \itKappa 𝛫
inoremap \itLambda 𝛬
inoremap \itMu 𝛭
inoremap \itNu 𝛮
inoremap \itXi 𝛯
inoremap \itOmicron 𝛰
inoremap \itPi 𝛱
inoremap \itRho 𝛲
inoremap \itvarTheta 𝛳
inoremap \itSigma 𝛴
inoremap \itTau 𝛵
inoremap \itUpsilon 𝛶
inoremap \itPhi 𝛷
inoremap \itChi 𝛸
inoremap \itPsi 𝛹
inoremap \itOmega 𝛺
inoremap \itnabla 𝛻
inoremap \italpha 𝛼
inoremap \itbeta 𝛽
inoremap \itgamma 𝛾
inoremap \itdelta 𝛿
inoremap \itvarepsilon 𝜀
inoremap \itzeta 𝜁
inoremap \iteta 𝜂
inoremap \ittheta 𝜃
inoremap \itiota 𝜄
inoremap \itkappa 𝜅
inoremap \itlambda 𝜆
inoremap \itmu 𝜇
inoremap \itnu 𝜈
inoremap \itxi 𝜉
inoremap \itomicron 𝜊
inoremap \itpi 𝜋
inoremap \itrho 𝜌
inoremap \itvarsigma 𝜍
inoremap \itsigma 𝜎
inoremap \ittau 𝜏
inoremap \itupsilon 𝜐
inoremap \itvarphi 𝜑
inoremap \itchi 𝜒
inoremap \itpsi 𝜓
inoremap \itomega 𝜔
inoremap \itpartial 𝜕
inoremap \itepsilon 𝜖
inoremap \itvartheta 𝜗
inoremap \itvarkappa 𝜘
inoremap \itphi 𝜙
inoremap \itvarrho 𝜚
inoremap \itvarpi 𝜛
inoremap \biAlpha 𝜜
inoremap \biBeta 𝜝
inoremap \biGamma 𝜞
inoremap \biDelta 𝜟
inoremap \biEpsilon 𝜠
inoremap \biZeta 𝜡
inoremap \biEta 𝜢
inoremap \biTheta 𝜣
inoremap \biIota 𝜤
inoremap \biKappa 𝜥
inoremap \biLambda 𝜦
inoremap \biMu 𝜧
inoremap \biNu 𝜨
inoremap \biXi 𝜩
inoremap \biOmicron 𝜪
inoremap \biPi 𝜫
inoremap \biRho 𝜬
inoremap \bivarTheta 𝜭
inoremap \biSigma 𝜮
inoremap \biTau 𝜯
inoremap \biUpsilon 𝜰
inoremap \biPhi 𝜱
inoremap \biChi 𝜲
inoremap \biPsi 𝜳
inoremap \biOmega 𝜴
inoremap \binabla 𝜵
inoremap \bialpha 𝜶
inoremap \bibeta 𝜷
inoremap \bigamma 𝜸
inoremap \bidelta 𝜹
inoremap \bivarepsilon 𝜺
inoremap \bizeta 𝜻
inoremap \bieta 𝜼
inoremap \bitheta 𝜽
inoremap \biiota 𝜾
inoremap \bikappa 𝜿
inoremap \bilambda 𝝀
inoremap \bimu 𝝁
inoremap \binu 𝝂
inoremap \bixi 𝝃
inoremap \biomicron 𝝄
inoremap \bipi 𝝅
inoremap \birho 𝝆
inoremap \bivarsigma 𝝇
inoremap \bisigma 𝝈
inoremap \bitau 𝝉
inoremap \biupsilon 𝝊
inoremap \bivarphi 𝝋
inoremap \bichi 𝝌
inoremap \bipsi 𝝍
inoremap \biomega 𝝎
inoremap \bipartial 𝝏
inoremap \biepsilon 𝝐
inoremap \bivartheta 𝝑
inoremap \bivarkappa 𝝒
inoremap \biphi 𝝓
inoremap \bivarrho 𝝔
inoremap \bivarpi 𝝕
inoremap \bsansAlpha 𝝖
inoremap \bsansBeta 𝝗
inoremap \bsansGamma 𝝘
inoremap \bsansDelta 𝝙
inoremap \bsansEpsilon 𝝚
inoremap \bsansZeta 𝝛
inoremap \bsansEta 𝝜
inoremap \bsansTheta 𝝝
inoremap \bsansIota 𝝞
inoremap \bsansKappa 𝝟
inoremap \bsansLambda 𝝠
inoremap \bsansMu 𝝡
inoremap \bsansNu 𝝢
inoremap \bsansXi 𝝣
inoremap \bsansOmicron 𝝤
inoremap \bsansPi 𝝥
inoremap \bsansRho 𝝦
inoremap \bsansvarTheta 𝝧
inoremap \bsansSigma 𝝨
inoremap \bsansTau 𝝩
inoremap \bsansUpsilon 𝝪
inoremap \bsansPhi 𝝫
inoremap \bsansChi 𝝬
inoremap \bsansPsi 𝝭
inoremap \bsansOmega 𝝮
inoremap \bsansnabla 𝝯
inoremap \bsansalpha 𝝰
inoremap \bsansbeta 𝝱
inoremap \bsansgamma 𝝲
inoremap \bsansdelta 𝝳
inoremap \bsansvarepsilon 𝝴
inoremap \bsanszeta 𝝵
inoremap \bsanseta 𝝶
inoremap \bsanstheta 𝝷
inoremap \bsansiota 𝝸
inoremap \bsanskappa 𝝹
inoremap \bsanslambda 𝝺
inoremap \bsansmu 𝝻
inoremap \bsansnu 𝝼
inoremap \bsansxi 𝝽
inoremap \bsansomicron 𝝾
inoremap \bsanspi 𝝿
inoremap \bsansrho 𝞀
inoremap \bsansvarsigma 𝞁
inoremap \bsanssigma 𝞂
inoremap \bsanstau 𝞃
inoremap \bsansupsilon 𝞄
inoremap \bsansvarphi 𝞅
inoremap \bsanschi 𝞆
inoremap \bsanspsi 𝞇
inoremap \bsansomega 𝞈
inoremap \bsanspartial 𝞉
inoremap \bsansepsilon 𝞊
inoremap \bsansvartheta 𝞋
inoremap \bsansvarkappa 𝞌
inoremap \bsansphi 𝞍
inoremap \bsansvarrho 𝞎
inoremap \bsansvarpi 𝞏
inoremap \bisansAlpha 𝞐
inoremap \bisansBeta 𝞑
inoremap \bisansGamma 𝞒
inoremap \bisansDelta 𝞓
inoremap \bisansEpsilon 𝞔
inoremap \bisansZeta 𝞕
inoremap \bisansEta 𝞖
inoremap \bisansTheta 𝞗
inoremap \bisansIota 𝞘
inoremap \bisansKappa 𝞙
inoremap \bisansLambda 𝞚
inoremap \bisansMu 𝞛
inoremap \bisansNu 𝞜
inoremap \bisansXi 𝞝
inoremap \bisansOmicron 𝞞
inoremap \bisansPi 𝞟
inoremap \bisansRho 𝞠
inoremap \bisansvarTheta 𝞡
inoremap \bisansSigma 𝞢
inoremap \bisansTau 𝞣
inoremap \bisansUpsilon 𝞤
inoremap \bisansPhi 𝞥
inoremap \bisansChi 𝞦
inoremap \bisansPsi 𝞧
inoremap \bisansOmega 𝞨
inoremap \bisansnabla 𝞩
inoremap \bisansalpha 𝞪
inoremap \bisansbeta 𝞫
inoremap \bisansgamma 𝞬
inoremap \bisansdelta 𝞭
inoremap \bisansvarepsilon 𝞮
inoremap \bisanszeta 𝞯
inoremap \bisanseta 𝞰
inoremap \bisanstheta 𝞱
inoremap \bisansiota 𝞲
inoremap \bisanskappa 𝞳
inoremap \bisanslambda 𝞴
inoremap \bisansmu 𝞵
inoremap \bisansnu 𝞶
inoremap \bisansxi 𝞷
inoremap \bisansomicron 𝞸
inoremap \bisanspi 𝞹
inoremap \bisansrho 𝞺
inoremap \bisansvarsigma 𝞻
inoremap \bisanssigma 𝞼
inoremap \bisanstau 𝞽
inoremap \bisansupsilon 𝞾
inoremap \bisansvarphi 𝞿
inoremap \bisanschi 𝟀
inoremap \bisanspsi 𝟁
inoremap \bisansomega 𝟂
inoremap \bisanspartial 𝟃
inoremap \bisansepsilon 𝟄
inoremap \bisansvartheta 𝟅
inoremap \bisansvarkappa 𝟆
inoremap \bisansphi 𝟇
inoremap \bisansvarrho 𝟈
inoremap \bisansvarpi 𝟉
inoremap \bfDigamma 𝟊
inoremap \bfdigamma 𝟋
inoremap \bfzero 𝟎
inoremap \bfone 𝟏
inoremap \bftwo 𝟐
inoremap \bfthree 𝟑
inoremap \bffour 𝟒
inoremap \bffive 𝟓
inoremap \bfsix 𝟔
inoremap \bfseven 𝟕
inoremap \bfeight 𝟖
inoremap \bfnine 𝟗
inoremap \bbzero 𝟘
inoremap \bbone 𝟙
inoremap \bbtwo 𝟚
inoremap \bbthree 𝟛
inoremap \bbfour 𝟜
inoremap \bbfive 𝟝
inoremap \bbsix 𝟞
inoremap \bbseven 𝟟
inoremap \bbeight 𝟠
inoremap \bbnine 𝟡
inoremap \sanszero 𝟢
inoremap \sansone 𝟣
inoremap \sanstwo 𝟤
inoremap \sansthree 𝟥
inoremap \sansfour 𝟦
inoremap \sansfive 𝟧
inoremap \sanssix 𝟨
inoremap \sansseven 𝟩
inoremap \sanseight 𝟪
inoremap \sansnine 𝟫
inoremap \bsanszero 𝟬
inoremap \bsansone 𝟭
inoremap \bsanstwo 𝟮
inoremap \bsansthree 𝟯
inoremap \bsansfour 𝟰
inoremap \bsansfive 𝟱
inoremap \bsanssix 𝟲
inoremap \bsansseven 𝟳
inoremap \bsanseight 𝟴
inoremap \bsansnine 𝟵
inoremap \ttzero 𝟶
inoremap \ttone 𝟷
inoremap \tttwo 𝟸
inoremap \ttthree 𝟹
inoremap \ttfour 𝟺
inoremap \ttfive 𝟻
inoremap \ttsix 𝟼
inoremap \ttseven 𝟽
inoremap \tteight 𝟾
inoremap \ttnine 𝟿
inoremap \:mahjong: 🀄
inoremap \:black_joker: 🃏
inoremap \:a: 🅰
inoremap \:b: 🅱
inoremap \:o2: 🅾
inoremap \:parking: 🅿
inoremap \:ab: 🆎
inoremap \:cl: 🆑
inoremap \:cool: 🆒
inoremap \:free: 🆓
inoremap \:id: 🆔
inoremap \:new: 🆕
inoremap \:ng: 🆖
inoremap \:ok: 🆗
inoremap \:sos: 🆘
inoremap \:up: 🆙
inoremap \:vs: 🆚
inoremap \:koko: 🈁
inoremap \:sa: 🈂
inoremap \:u7121: 🈚
inoremap \:u6307: 🈯
inoremap \:u7981: 🈲
inoremap \:u7a7a: 🈳
inoremap \:u5408: 🈴
inoremap \:u6e80: 🈵
inoremap \:u6709: 🈶
inoremap \:u6708: 🈷
inoremap \:u7533: 🈸
inoremap \:u5272: 🈹
inoremap \:u55b6: 🈺
inoremap \:ideograph_advantage: 🉐
inoremap \:accept: 🉑
inoremap \:cyclone: 🌀
inoremap \:foggy: 🌁
inoremap \:closed_umbrella: 🌂
inoremap \:night_with_stars: 🌃
inoremap \:sunrise_over_mountains: 🌄
inoremap \:sunrise: 🌅
inoremap \:city_sunset: 🌆
inoremap \:city_sunrise: 🌇
inoremap \:rainbow: 🌈
inoremap \:bridge_at_night: 🌉
inoremap \:ocean: 🌊
inoremap \:volcano: 🌋
inoremap \:milky_way: 🌌
inoremap \:earth_africa: 🌍
inoremap \:earth_americas: 🌎
inoremap \:earth_asia: 🌏
inoremap \:globe_with_meridians: 🌐
inoremap \:new_moon: 🌑
inoremap \:waxing_crescent_moon: 🌒
inoremap \:first_quarter_moon: 🌓
inoremap \:moon: 🌔
inoremap \:full_moon: 🌕
inoremap \:waning_gibbous_moon: 🌖
inoremap \:last_quarter_moon: 🌗
inoremap \:waning_crescent_moon: 🌘
inoremap \:crescent_moon: 🌙
inoremap \:new_moon_with_face: 🌚
inoremap \:first_quarter_moon_with_face: 🌛
inoremap \:last_quarter_moon_with_face: 🌜
inoremap \:full_moon_with_face: 🌝
inoremap \:sun_with_face: 🌞
inoremap \:star2: 🌟
inoremap \:stars: 🌠
inoremap \:hotdog: 🌭
inoremap \:taco: 🌮
inoremap \:burrito: 🌯
inoremap \:chestnut: 🌰
inoremap \:seedling: 🌱
inoremap \:evergreen_tree: 🌲
inoremap \:deciduous_tree: 🌳
inoremap \:palm_tree: 🌴
inoremap \:cactus: 🌵
inoremap \:tulip: 🌷
inoremap \:cherry_blossom: 🌸
inoremap \:rose: 🌹
inoremap \:hibiscus: 🌺
inoremap \:sunflower: 🌻
inoremap \:blossom: 🌼
inoremap \:corn: 🌽
inoremap \:ear_of_rice: 🌾
inoremap \:herb: 🌿
inoremap \:four_leaf_clover: 🍀
inoremap \:maple_leaf: 🍁
inoremap \:fallen_leaf: 🍂
inoremap \:leaves: 🍃
inoremap \:mushroom: 🍄
inoremap \:tomato: 🍅
inoremap \:eggplant: 🍆
inoremap \:grapes: 🍇
inoremap \:melon: 🍈
inoremap \:watermelon: 🍉
inoremap \:tangerine: 🍊
inoremap \:lemon: 🍋
inoremap \:banana: 🍌
inoremap \:pineapple: 🍍
inoremap \:apple: 🍎
inoremap \:green_apple: 🍏
inoremap \:pear: 🍐
inoremap \:peach: 🍑
inoremap \:cherries: 🍒
inoremap \:strawberry: 🍓
inoremap \:hamburger: 🍔
inoremap \:pizza: 🍕
inoremap \:meat_on_bone: 🍖
inoremap \:poultry_leg: 🍗
inoremap \:rice_cracker: 🍘
inoremap \:rice_ball: 🍙
inoremap \:rice: 🍚
inoremap \:curry: 🍛
inoremap \:ramen: 🍜
inoremap \:spaghetti: 🍝
inoremap \:bread: 🍞
inoremap \:fries: 🍟
inoremap \:sweet_potato: 🍠
inoremap \:dango: 🍡
inoremap \:oden: 🍢
inoremap \:sushi: 🍣
inoremap \:fried_shrimp: 🍤
inoremap \:fish_cake: 🍥
inoremap \:icecream: 🍦
inoremap \:shaved_ice: 🍧
inoremap \:ice_cream: 🍨
inoremap \:doughnut: 🍩
inoremap \:cookie: 🍪
inoremap \:chocolate_bar: 🍫
inoremap \:candy: 🍬
inoremap \:lollipop: 🍭
inoremap \:custard: 🍮
inoremap \:honey_pot: 🍯
inoremap \:cake: 🍰
inoremap \:bento: 🍱
inoremap \:stew: 🍲
inoremap \:fried_egg: 🍳
inoremap \:fork_and_knife: 🍴
inoremap \:tea: 🍵
inoremap \:sake: 🍶
inoremap \:wine_glass: 🍷
inoremap \:cocktail: 🍸
inoremap \:tropical_drink: 🍹
inoremap \:beer: 🍺
inoremap \:beers: 🍻
inoremap \:baby_bottle: 🍼
inoremap \:champagne: 🍾
inoremap \:popcorn: 🍿
inoremap \:ribbon: 🎀
inoremap \:gift: 🎁
inoremap \:birthday: 🎂
inoremap \:jack_o_lantern: 🎃
inoremap \:christmas_tree: 🎄
inoremap \:santa: 🎅
inoremap \:fireworks: 🎆
inoremap \:sparkler: 🎇
inoremap \:balloon: 🎈
inoremap \:tada: 🎉
inoremap \:confetti_ball: 🎊
inoremap \:tanabata_tree: 🎋
inoremap \:crossed_flags: 🎌
inoremap \:bamboo: 🎍
inoremap \:dolls: 🎎
inoremap \:flags: 🎏
inoremap \:wind_chime: 🎐
inoremap \:rice_scene: 🎑
inoremap \:school_satchel: 🎒
inoremap \:mortar_board: 🎓
inoremap \:carousel_horse: 🎠
inoremap \:ferris_wheel: 🎡
inoremap \:roller_coaster: 🎢
inoremap \:fishing_pole_and_fish: 🎣
inoremap \:microphone: 🎤
inoremap \:movie_camera: 🎥
inoremap \:cinema: 🎦
inoremap \:headphones: 🎧
inoremap \:art: 🎨
inoremap \:tophat: 🎩
inoremap \:circus_tent: 🎪
inoremap \:ticket: 🎫
inoremap \:clapper: 🎬
inoremap \:performing_arts: 🎭
inoremap \:video_game: 🎮
inoremap \:dart: 🎯
inoremap \:slot_machine: 🎰
inoremap \:8ball: 🎱
inoremap \:game_die: 🎲
inoremap \:bowling: 🎳
inoremap \:flower_playing_cards: 🎴
inoremap \:musical_note: 🎵
inoremap \:notes: 🎶
inoremap \:saxophone: 🎷
inoremap \:guitar: 🎸
inoremap \:musical_keyboard: 🎹
inoremap \:trumpet: 🎺
inoremap \:violin: 🎻
inoremap \:musical_score: 🎼
inoremap \:running_shirt_with_sash: 🎽
inoremap \:tennis: 🎾
inoremap \:ski: 🎿
inoremap \:basketball: 🏀
inoremap \:checkered_flag: 🏁
inoremap \:snowboarder: 🏂
inoremap \:runner: 🏃
inoremap \:surfer: 🏄
inoremap \:sports_medal: 🏅
inoremap \:trophy: 🏆
inoremap \:horse_racing: 🏇
inoremap \:football: 🏈
inoremap \:rugby_football: 🏉
inoremap \:swimmer: 🏊
inoremap \:cricket_bat_and_ball: 🏏
inoremap \:volleyball: 🏐
inoremap \:field_hockey_stick_and_ball: 🏑
inoremap \:ice_hockey_stick_and_puck: 🏒
inoremap \:table_tennis_paddle_and_ball: 🏓
inoremap \:house: 🏠
inoremap \:house_with_garden: 🏡
inoremap \:office: 🏢
inoremap \:post_office: 🏣
inoremap \:european_post_office: 🏤
inoremap \:hospital: 🏥
inoremap \:bank: 🏦
inoremap \:atm: 🏧
inoremap \:hotel: 🏨
inoremap \:love_hotel: 🏩
inoremap \:convenience_store: 🏪
inoremap \:school: 🏫
inoremap \:department_store: 🏬
inoremap \:factory: 🏭
inoremap \:izakaya_lantern: 🏮
inoremap \:japanese_castle: 🏯
inoremap \:european_castle: 🏰
inoremap \:waving_black_flag: 🏴
inoremap \:badminton_racquet_and_shuttlecock: 🏸
inoremap \:bow_and_arrow: 🏹
inoremap \:amphora: 🏺
inoremap \:skin-tone-2: 🏻
inoremap \:skin-tone-3: 🏼
inoremap \:skin-tone-4: 🏽
inoremap \:skin-tone-5: 🏾
inoremap \:skin-tone-6: 🏿
inoremap \:rat: 🐀
inoremap \:mouse2: 🐁
inoremap \:ox: 🐂
inoremap \:water_buffalo: 🐃
inoremap \:cow2: 🐄
inoremap \:tiger2: 🐅
inoremap \:leopard: 🐆
inoremap \:rabbit2: 🐇
inoremap \:cat2: 🐈
inoremap \:dragon: 🐉
inoremap \:crocodile: 🐊
inoremap \:whale2: 🐋
inoremap \:snail: 🐌
inoremap \:snake: 🐍
inoremap \:racehorse: 🐎
inoremap \:ram: 🐏
inoremap \:goat: 🐐
inoremap \:sheep: 🐑
inoremap \:monkey: 🐒
inoremap \:rooster: 🐓
inoremap \:chicken: 🐔
inoremap \:dog2: 🐕
inoremap \:pig2: 🐖
inoremap \:boar: 🐗
inoremap \:elephant: 🐘
inoremap \:octopus: 🐙
inoremap \:shell: 🐚
inoremap \:bug: 🐛
inoremap \:ant: 🐜
inoremap \:bee: 🐝
inoremap \:ladybug: 🐞
inoremap \:fish: 🐟
inoremap \:tropical_fish: 🐠
inoremap \:blowfish: 🐡
inoremap \:turtle: 🐢
inoremap \:hatching_chick: 🐣
inoremap \:baby_chick: 🐤
inoremap \:hatched_chick: 🐥
inoremap \:bird: 🐦
inoremap \:penguin: 🐧
inoremap \:koala: 🐨
inoremap \:poodle: 🐩
inoremap \:dromedary_camel: 🐪
inoremap \:camel: 🐫
inoremap \:dolphin: 🐬
inoremap \:mouse: 🐭
inoremap \:cow: 🐮
inoremap \:tiger: 🐯
inoremap \:rabbit: 🐰
inoremap \:cat: 🐱
inoremap \:dragon_face: 🐲
inoremap \:whale: 🐳
inoremap \:horse: 🐴
inoremap \:monkey_face: 🐵
inoremap \:dog: 🐶
inoremap \:pig: 🐷
inoremap \:frog: 🐸
inoremap \:hamster: 🐹
inoremap \:wolf: 🐺
inoremap \:bear: 🐻
inoremap \:panda_face: 🐼
inoremap \:pig_nose: 🐽
inoremap \:feet: 🐾
inoremap \:eyes: 👀
inoremap \:ear: 👂
inoremap \:nose: 👃
inoremap \:lips: 👄
inoremap \:tongue: 👅
inoremap \:point_up_2: 👆
inoremap \:point_down: 👇
inoremap \:point_left: 👈
inoremap \:point_right: 👉
inoremap \:facepunch: 👊
inoremap \:wave: 👋
inoremap \:ok_hand: 👌
inoremap \:+1: 👍
inoremap \:-1: 👎
inoremap \:clap: 👏
inoremap \:open_hands: 👐
inoremap \:crown: 👑
inoremap \:womans_hat: 👒
inoremap \:eyeglasses: 👓
inoremap \:necktie: 👔
inoremap \:shirt: 👕
inoremap \:jeans: 👖
inoremap \:dress: 👗
inoremap \:kimono: 👘
inoremap \:bikini: 👙
inoremap \:womans_clothes: 👚
inoremap \:purse: 👛
inoremap \:handbag: 👜
inoremap \:pouch: 👝
inoremap \:mans_shoe: 👞
inoremap \:athletic_shoe: 👟
inoremap \:high_heel: 👠
inoremap \:sandal: 👡
inoremap \:boot: 👢
inoremap \:footprints: 👣
inoremap \:bust_in_silhouette: 👤
inoremap \:busts_in_silhouette: 👥
inoremap \:boy: 👦
inoremap \:girl: 👧
inoremap \:man: 👨
inoremap \:woman: 👩
inoremap \:family: 👪
inoremap \:couple: 👫
inoremap \:two_men_holding_hands: 👬
inoremap \:two_women_holding_hands: 👭
inoremap \:cop: 👮
inoremap \:dancers: 👯
inoremap \:bride_with_veil: 👰
inoremap \:person_with_blond_hair: 👱
inoremap \:man_with_gua_pi_mao: 👲
inoremap \:man_with_turban: 👳
inoremap \:older_man: 👴
inoremap \:older_woman: 👵
inoremap \:baby: 👶
inoremap \:construction_worker: 👷
inoremap \:princess: 👸
inoremap \:japanese_ogre: 👹
inoremap \:japanese_goblin: 👺
inoremap \:ghost: 👻
inoremap \:angel: 👼
inoremap \:alien: 👽
inoremap \:space_invader: 👾
inoremap \:imp: 👿
inoremap \:skull: 💀
inoremap \:information_desk_person: 💁
inoremap \:guardsman: 💂
inoremap \:dancer: 💃
inoremap \:lipstick: 💄
inoremap \:nail_care: 💅
inoremap \:massage: 💆
inoremap \:haircut: 💇
inoremap \:barber: 💈
inoremap \:syringe: 💉
inoremap \:pill: 💊
inoremap \:kiss: 💋
inoremap \:love_letter: 💌
inoremap \:ring: 💍
inoremap \:gem: 💎
inoremap \:couplekiss: 💏
inoremap \:bouquet: 💐
inoremap \:couple_with_heart: 💑
inoremap \:wedding: 💒
inoremap \:heartbeat: 💓
inoremap \:broken_heart: 💔
inoremap \:two_hearts: 💕
inoremap \:sparkling_heart: 💖
inoremap \:heartpulse: 💗
inoremap \:cupid: 💘
inoremap \:blue_heart: 💙
inoremap \:green_heart: 💚
inoremap \:yellow_heart: 💛
inoremap \:purple_heart: 💜
inoremap \:gift_heart: 💝
inoremap \:revolving_hearts: 💞
inoremap \:heart_decoration: 💟
inoremap \:diamond_shape_with_a_dot_inside: 💠
inoremap \:bulb: 💡
inoremap \:anger: 💢
inoremap \:bomb: 💣
inoremap \:zzz: 💤
inoremap \:boom: 💥
inoremap \:sweat_drops: 💦
inoremap \:droplet: 💧
inoremap \:dash: 💨
inoremap \:hankey: 💩
inoremap \:muscle: 💪
inoremap \:dizzy: 💫
inoremap \:speech_balloon: 💬
inoremap \:thought_balloon: 💭
inoremap \:white_flower: 💮
inoremap \:100: 💯
inoremap \:moneybag: 💰
inoremap \:currency_exchange: 💱
inoremap \:heavy_dollar_sign: 💲
inoremap \:credit_card: 💳
inoremap \:yen: 💴
inoremap \:dollar: 💵
inoremap \:euro: 💶
inoremap \:pound: 💷
inoremap \:money_with_wings: 💸
inoremap \:chart: 💹
inoremap \:seat: 💺
inoremap \:computer: 💻
inoremap \:briefcase: 💼
inoremap \:minidisc: 💽
inoremap \:floppy_disk: 💾
inoremap \:cd: 💿
inoremap \:dvd: 📀
inoremap \:file_folder: 📁
inoremap \:open_file_folder: 📂
inoremap \:page_with_curl: 📃
inoremap \:page_facing_up: 📄
inoremap \:date: 📅
inoremap \:calendar: 📆
inoremap \:card_index: 📇
inoremap \:chart_with_upwards_trend: 📈
inoremap \:chart_with_downwards_trend: 📉
inoremap \:bar_chart: 📊
inoremap \:clipboard: 📋
inoremap \:pushpin: 📌
inoremap \:round_pushpin: 📍
inoremap \:paperclip: 📎
inoremap \:straight_ruler: 📏
inoremap \:triangular_ruler: 📐
inoremap \:bookmark_tabs: 📑
inoremap \:ledger: 📒
inoremap \:notebook: 📓
inoremap \:notebook_with_decorative_cover: 📔
inoremap \:closed_book: 📕
inoremap \:book: 📖
inoremap \:green_book: 📗
inoremap \:blue_book: 📘
inoremap \:orange_book: 📙
inoremap \:books: 📚
inoremap \:name_badge: 📛
inoremap \:scroll: 📜
inoremap \:memo: 📝
inoremap \:telephone_receiver: 📞
inoremap \:pager: 📟
inoremap \:fax: 📠
inoremap \:satellite: 📡
inoremap \:loudspeaker: 📢
inoremap \:mega: 📣
inoremap \:outbox_tray: 📤
inoremap \:inbox_tray: 📥
inoremap \:package: 📦
inoremap \:e-mail: 📧
inoremap \:incoming_envelope: 📨
inoremap \:envelope_with_arrow: 📩
inoremap \:mailbox_closed: 📪
inoremap \:mailbox: 📫
inoremap \:mailbox_with_mail: 📬
inoremap \:mailbox_with_no_mail: 📭
inoremap \:postbox: 📮
inoremap \:postal_horn: 📯
inoremap \:newspaper: 📰
inoremap \:iphone: 📱
inoremap \:calling: 📲
inoremap \:vibration_mode: 📳
inoremap \:mobile_phone_off: 📴
inoremap \:no_mobile_phones: 📵
inoremap \:signal_strength: 📶
inoremap \:camera: 📷
inoremap \:camera_with_flash: 📸
inoremap \:video_camera: 📹
inoremap \:tv: 📺
inoremap \:radio: 📻
inoremap \:vhs: 📼
inoremap \:prayer_beads: 📿
inoremap \:twisted_rightwards_arrows: 🔀
inoremap \:repeat: 🔁
inoremap \:repeat_one: 🔂
inoremap \:arrows_clockwise: 🔃
inoremap \:arrows_counterclockwise: 🔄
inoremap \:low_brightness: 🔅
inoremap \:high_brightness: 🔆
inoremap \:mute: 🔇
inoremap \:speaker: 🔈
inoremap \:sound: 🔉
inoremap \:loud_sound: 🔊
inoremap \:battery: 🔋
inoremap \:electric_plug: 🔌
inoremap \:mag: 🔍
inoremap \:mag_right: 🔎
inoremap \:lock_with_ink_pen: 🔏
inoremap \:closed_lock_with_key: 🔐
inoremap \:key: 🔑
inoremap \:lock: 🔒
inoremap \:unlock: 🔓
inoremap \:bell: 🔔
inoremap \:no_bell: 🔕
inoremap \:bookmark: 🔖
inoremap \:link: 🔗
inoremap \:radio_button: 🔘
inoremap \:back: 🔙
inoremap \:end: 🔚
inoremap \:on: 🔛
inoremap \:soon: 🔜
inoremap \:top: 🔝
inoremap \:underage: 🔞
inoremap \:keycap_ten: 🔟
inoremap \:capital_abcd: 🔠
inoremap \:abcd: 🔡
inoremap \:1234: 🔢
inoremap \:symbols: 🔣
inoremap \:abc: 🔤
inoremap \:fire: 🔥
inoremap \:flashlight: 🔦
inoremap \:wrench: 🔧
inoremap \:hammer: 🔨
inoremap \:nut_and_bolt: 🔩
inoremap \:hocho: 🔪
inoremap \:gun: 🔫
inoremap \:microscope: 🔬
inoremap \:telescope: 🔭
inoremap \:crystal_ball: 🔮
inoremap \:six_pointed_star: 🔯
inoremap \:beginner: 🔰
inoremap \:trident: 🔱
inoremap \:black_square_button: 🔲
inoremap \:white_square_button: 🔳
inoremap \:red_circle: 🔴
inoremap \:large_blue_circle: 🔵
inoremap \:large_orange_diamond: 🔶
inoremap \:large_blue_diamond: 🔷
inoremap \:small_orange_diamond: 🔸
inoremap \:small_blue_diamond: 🔹
inoremap \:small_red_triangle: 🔺
inoremap \:small_red_triangle_down: 🔻
inoremap \:arrow_up_small: 🔼
inoremap \:arrow_down_small: 🔽
inoremap \:kaaba: 🕋
inoremap \:mosque: 🕌
inoremap \:synagogue: 🕍
inoremap \:menorah_with_nine_branches: 🕎
inoremap \:clock1: 🕐
inoremap \:clock2: 🕑
inoremap \:clock3: 🕒
inoremap \:clock4: 🕓
inoremap \:clock5: 🕔
inoremap \:clock6: 🕕
inoremap \:clock7: 🕖
inoremap \:clock8: 🕗
inoremap \:clock9: 🕘
inoremap \:clock10: 🕙
inoremap \:clock11: 🕚
inoremap \:clock12: 🕛
inoremap \:clock130: 🕜
inoremap \:clock230: 🕝
inoremap \:clock330: 🕞
inoremap \:clock430: 🕟
inoremap \:clock530: 🕠
inoremap \:clock630: 🕡
inoremap \:clock730: 🕢
inoremap \:clock830: 🕣
inoremap \:clock930: 🕤
inoremap \:clock1030: 🕥
inoremap \:clock1130: 🕦
inoremap \:clock1230: 🕧
inoremap \:man_dancing: 🕺
inoremap \:middle_finger: 🖕
inoremap \:spock-hand: 🖖
inoremap \:black_heart: 🖤
inoremap \:mount_fuji: 🗻
inoremap \:tokyo_tower: 🗼
inoremap \:statue_of_liberty: 🗽
inoremap \:japan: 🗾
inoremap \:moyai: 🗿
inoremap \:grinning: 😀
inoremap \:grin: 😁
inoremap \:joy: 😂
inoremap \:smiley: 😃
inoremap \:smile: 😄
inoremap \:sweat_smile: 😅
inoremap \:laughing: 😆
inoremap \:innocent: 😇
inoremap \:smiling_imp: 😈
inoremap \:wink: 😉
inoremap \:blush: 😊
inoremap \:yum: 😋
inoremap \:relieved: 😌
inoremap \:heart_eyes: 😍
inoremap \:sunglasses: 😎
inoremap \:smirk: 😏
inoremap \:neutral_face: 😐
inoremap \:expressionless: 😑
inoremap \:unamused: 😒
inoremap \:sweat: 😓
inoremap \:pensive: 😔
inoremap \:confused: 😕
inoremap \:confounded: 😖
inoremap \:kissing: 😗
inoremap \:kissing_heart: 😘
inoremap \:kissing_smiling_eyes: 😙
inoremap \:kissing_closed_eyes: 😚
inoremap \:stuck_out_tongue: 😛
inoremap \:stuck_out_tongue_winking_eye: 😜
inoremap \:stuck_out_tongue_closed_eyes: 😝
inoremap \:disappointed: 😞
inoremap \:worried: 😟
inoremap \:angry: 😠
inoremap \:rage: 😡
inoremap \:cry: 😢
inoremap \:persevere: 😣
inoremap \:triumph: 😤
inoremap \:disappointed_relieved: 😥
inoremap \:frowning: 😦
inoremap \:anguished: 😧
inoremap \:fearful: 😨
inoremap \:weary: 😩
inoremap \:sleepy: 😪
inoremap \:tired_face: 😫
inoremap \:grimacing: 😬
inoremap \:sob: 😭
inoremap \:open_mouth: 😮
inoremap \:hushed: 😯
inoremap \:cold_sweat: 😰
inoremap \:scream: 😱
inoremap \:astonished: 😲
inoremap \:flushed: 😳
inoremap \:sleeping: 😴
inoremap \:dizzy_face: 😵
inoremap \:no_mouth: 😶
inoremap \:mask: 😷
inoremap \:smile_cat: 😸
inoremap \:joy_cat: 😹
inoremap \:smiley_cat: 😺
inoremap \:heart_eyes_cat: 😻
inoremap \:smirk_cat: 😼
inoremap \:kissing_cat: 😽
inoremap \:pouting_cat: 😾
inoremap \:crying_cat_face: 😿
inoremap \:scream_cat: 🙀
inoremap \:slightly_frowning_face: 🙁
inoremap \:slightly_smiling_face: 🙂
inoremap \:upside_down_face: 🙃
inoremap \:face_with_rolling_eyes: 🙄
inoremap \:no_good: 🙅
inoremap \:ok_woman: 🙆
inoremap \:bow: 🙇
inoremap \:see_no_evil: 🙈
inoremap \:hear_no_evil: 🙉
inoremap \:speak_no_evil: 🙊
inoremap \:raising_hand: 🙋
inoremap \:raised_hands: 🙌
inoremap \:person_frowning: 🙍
inoremap \:person_with_pouting_face: 🙎
inoremap \:pray: 🙏
inoremap \:rocket: 🚀
inoremap \:helicopter: 🚁
inoremap \:steam_locomotive: 🚂
inoremap \:railway_car: 🚃
inoremap \:bullettrain_side: 🚄
inoremap \:bullettrain_front: 🚅
inoremap \:train2: 🚆
inoremap \:metro: 🚇
inoremap \:light_rail: 🚈
inoremap \:station: 🚉
inoremap \:tram: 🚊
inoremap \:train: 🚋
inoremap \:bus: 🚌
inoremap \:oncoming_bus: 🚍
inoremap \:trolleybus: 🚎
inoremap \:busstop: 🚏
inoremap \:minibus: 🚐
inoremap \:ambulance: 🚑
inoremap \:fire_engine: 🚒
inoremap \:police_car: 🚓
inoremap \:oncoming_police_car: 🚔
inoremap \:taxi: 🚕
inoremap \:oncoming_taxi: 🚖
inoremap \:car: 🚗
inoremap \:oncoming_automobile: 🚘
inoremap \:blue_car: 🚙
inoremap \:truck: 🚚
inoremap \:articulated_lorry: 🚛
inoremap \:tractor: 🚜
inoremap \:monorail: 🚝
inoremap \:mountain_railway: 🚞
inoremap \:suspension_railway: 🚟
inoremap \:mountain_cableway: 🚠
inoremap \:aerial_tramway: 🚡
inoremap \:ship: 🚢
inoremap \:rowboat: 🚣
inoremap \:speedboat: 🚤
inoremap \:traffic_light: 🚥
inoremap \:vertical_traffic_light: 🚦
inoremap \:construction: 🚧
inoremap \:rotating_light: 🚨
inoremap \:triangular_flag_on_post: 🚩
inoremap \:door: 🚪
inoremap \:no_entry_sign: 🚫
inoremap \:smoking: 🚬
inoremap \:no_smoking: 🚭
inoremap \:put_litter_in_its_place: 🚮
inoremap \:do_not_litter: 🚯
inoremap \:potable_water: 🚰
inoremap \:non-potable_water: 🚱
inoremap \:bike: 🚲
inoremap \:no_bicycles: 🚳
inoremap \:bicyclist: 🚴
inoremap \:mountain_bicyclist: 🚵
inoremap \:walking: 🚶
inoremap \:no_pedestrians: 🚷
inoremap \:children_crossing: 🚸
inoremap \:mens: 🚹
inoremap \:womens: 🚺
inoremap \:restroom: 🚻
inoremap \:baby_symbol: 🚼
inoremap \:toilet: 🚽
inoremap \:wc: 🚾
inoremap \:shower: 🚿
inoremap \:bath: 🛀
inoremap \:bathtub: 🛁
inoremap \:passport_control: 🛂
inoremap \:customs: 🛃
inoremap \:baggage_claim: 🛄
inoremap \:left_luggage: 🛅
inoremap \:sleeping_accommodation: 🛌
inoremap \:place_of_worship: 🛐
inoremap \:octagonal_sign: 🛑
inoremap \:shopping_trolley: 🛒
inoremap \:hindu_temple: 🛕
inoremap \:hut: 🛖
inoremap \:elevator: 🛗
inoremap \:airplane_departure: 🛫
inoremap \:airplane_arriving: 🛬
inoremap \:scooter: 🛴
inoremap \:motor_scooter: 🛵
inoremap \:canoe: 🛶
inoremap \:sled: 🛷
inoremap \:flying_saucer: 🛸
inoremap \:skateboard: 🛹
inoremap \:auto_rickshaw: 🛺
inoremap \:pickup_truck: 🛻
inoremap \:roller_skate: 🛼
inoremap \:large_orange_circle: 🟠
inoremap \:large_yellow_circle: 🟡
inoremap \:large_green_circle: 🟢
inoremap \:large_purple_circle: 🟣
inoremap \:large_brown_circle: 🟤
inoremap \:large_red_square: 🟥
inoremap \:large_blue_square: 🟦
inoremap \:large_orange_square: 🟧
inoremap \:large_yellow_square: 🟨
inoremap \:large_green_square: 🟩
inoremap \:large_purple_square: 🟪
inoremap \:large_brown_square: 🟫
inoremap \:pinched_fingers: 🤌
inoremap \:white_heart: 🤍
inoremap \:brown_heart: 🤎
inoremap \:pinching_hand: 🤏
inoremap \:zipper_mouth_face: 🤐
inoremap \:money_mouth_face: 🤑
inoremap \:face_with_thermometer: 🤒
inoremap \:nerd_face: 🤓
inoremap \:thinking_face: 🤔
inoremap \:face_with_head_bandage: 🤕
inoremap \:robot_face: 🤖
inoremap \:hugging_face: 🤗
inoremap \:the_horns: 🤘
inoremap \:call_me_hand: 🤙
inoremap \:raised_back_of_hand: 🤚
inoremap \:left-facing_fist: 🤛
inoremap \:right-facing_fist: 🤜
inoremap \:handshake: 🤝
inoremap \:crossed_fingers: 🤞
inoremap \:i_love_you_hand_sign: 🤟
inoremap \:face_with_cowboy_hat: 🤠
inoremap \:clown_face: 🤡
inoremap \:nauseated_face: 🤢
inoremap \:rolling_on_the_floor_laughing: 🤣
inoremap \:drooling_face: 🤤
inoremap \:lying_face: 🤥
inoremap \:face_palm: 🤦
inoremap \:sneezing_face: 🤧
inoremap \:face_with_raised_eyebrow: 🤨
inoremap \:star-struck: 🤩
inoremap \:zany_face: 🤪
inoremap \:shushing_face: 🤫
inoremap \:face_with_symbols_on_mouth: 🤬
inoremap \:face_with_hand_over_mouth: 🤭
inoremap \:face_vomiting: 🤮
inoremap \:exploding_head: 🤯
inoremap \:pregnant_woman: 🤰
inoremap \:breast-feeding: 🤱
inoremap \:palms_up_together: 🤲
inoremap \:selfie: 🤳
inoremap \:prince: 🤴
inoremap \:person_in_tuxedo: 🤵
inoremap \:mrs_claus: 🤶
inoremap \:shrug: 🤷
inoremap \:person_doing_cartwheel: 🤸
inoremap \:juggling: 🤹
inoremap \:fencer: 🤺
inoremap \:wrestlers: 🤼
inoremap \:water_polo: 🤽
inoremap \:handball: 🤾
inoremap \:diving_mask: 🤿
inoremap \:wilted_flower: 🥀
inoremap \:drum_with_drumsticks: 🥁
inoremap \:clinking_glasses: 🥂
inoremap \:tumbler_glass: 🥃
inoremap \:spoon: 🥄
inoremap \:goal_net: 🥅
inoremap \:first_place_medal: 🥇
inoremap \:second_place_medal: 🥈
inoremap \:third_place_medal: 🥉
inoremap \:boxing_glove: 🥊
inoremap \:martial_arts_uniform: 🥋
inoremap \:curling_stone: 🥌
inoremap \:lacrosse: 🥍
inoremap \:softball: 🥎
inoremap \:flying_disc: 🥏
inoremap \:croissant: 🥐
inoremap \:avocado: 🥑
inoremap \:cucumber: 🥒
inoremap \:bacon: 🥓
inoremap \:potato: 🥔
inoremap \:carrot: 🥕
inoremap \:baguette_bread: 🥖
inoremap \:green_salad: 🥗
inoremap \:shallow_pan_of_food: 🥘
inoremap \:stuffed_flatbread: 🥙
inoremap \:egg: 🥚
inoremap \:glass_of_milk: 🥛
inoremap \:peanuts: 🥜
inoremap \:kiwifruit: 🥝
inoremap \:pancakes: 🥞
inoremap \:dumpling: 🥟
inoremap \:fortune_cookie: 🥠
inoremap \:takeout_box: 🥡
inoremap \:chopsticks: 🥢
inoremap \:bowl_with_spoon: 🥣
inoremap \:cup_with_straw: 🥤
inoremap \:coconut: 🥥
inoremap \:broccoli: 🥦
inoremap \:pie: 🥧
inoremap \:pretzel: 🥨
inoremap \:cut_of_meat: 🥩
inoremap \:sandwich: 🥪
inoremap \:canned_food: 🥫
inoremap \:leafy_green: 🥬
inoremap \:mango: 🥭
inoremap \:moon_cake: 🥮
inoremap \:bagel: 🥯
inoremap \:smiling_face_with_3_hearts: 🥰
inoremap \:yawning_face: 🥱
inoremap \:smiling_face_with_tear: 🥲
inoremap \:partying_face: 🥳
inoremap \:woozy_face: 🥴
inoremap \:hot_face: 🥵
inoremap \:cold_face: 🥶
inoremap \:ninja: 🥷
inoremap \:disguised_face: 🥸
inoremap \:pleading_face: 🥺
inoremap \:sari: 🥻
inoremap \:lab_coat: 🥼
inoremap \:goggles: 🥽
inoremap \:hiking_boot: 🥾
inoremap \:womans_flat_shoe: 🥿
inoremap \:crab: 🦀
inoremap \:lion_face: 🦁
inoremap \:scorpion: 🦂
inoremap \:turkey: 🦃
inoremap \:unicorn_face: 🦄
inoremap \:eagle: 🦅
inoremap \:duck: 🦆
inoremap \:bat: 🦇
inoremap \:shark: 🦈
inoremap \:owl: 🦉
inoremap \:fox_face: 🦊
inoremap \:butterfly: 🦋
inoremap \:deer: 🦌
inoremap \:gorilla: 🦍
inoremap \:lizard: 🦎
inoremap \:rhinoceros: 🦏
inoremap \:shrimp: 🦐
inoremap \:squid: 🦑
inoremap \:giraffe_face: 🦒
inoremap \:zebra_face: 🦓
inoremap \:hedgehog: 🦔
inoremap \:sauropod: 🦕
inoremap \:t-rex: 🦖
inoremap \:cricket: 🦗
inoremap \:kangaroo: 🦘
inoremap \:llama: 🦙
inoremap \:peacock: 🦚
inoremap \:hippopotamus: 🦛
inoremap \:parrot: 🦜
inoremap \:raccoon: 🦝
inoremap \:lobster: 🦞
inoremap \:mosquito: 🦟
inoremap \:microbe: 🦠
inoremap \:badger: 🦡
inoremap \:swan: 🦢
inoremap \:mammoth: 🦣
inoremap \:dodo: 🦤
inoremap \:sloth: 🦥
inoremap \:otter: 🦦
inoremap \:orangutan: 🦧
inoremap \:skunk: 🦨
inoremap \:flamingo: 🦩
inoremap \:oyster: 🦪
inoremap \:beaver: 🦫
inoremap \:bison: 🦬
inoremap \:seal: 🦭
inoremap \:guide_dog: 🦮
inoremap \:probing_cane: 🦯
inoremap \:bone: 🦴
inoremap \:leg: 🦵
inoremap \:foot: 🦶
inoremap \:tooth: 🦷
inoremap \:superhero: 🦸
inoremap \:supervillain: 🦹
inoremap \:safety_vest: 🦺
inoremap \:ear_with_hearing_aid: 🦻
inoremap \:motorized_wheelchair: 🦼
inoremap \:manual_wheelchair: 🦽
inoremap \:mechanical_arm: 🦾
inoremap \:mechanical_leg: 🦿
inoremap \:cheese_wedge: 🧀
inoremap \:cupcake: 🧁
inoremap \:salt: 🧂
inoremap \:beverage_box: 🧃
inoremap \:garlic: 🧄
inoremap \:onion: 🧅
inoremap \:falafel: 🧆
inoremap \:waffle: 🧇
inoremap \:butter: 🧈
inoremap \:mate_drink: 🧉
inoremap \:ice_cube: 🧊
inoremap \:bubble_tea: 🧋
inoremap \:standing_person: 🧍
inoremap \:kneeling_person: 🧎
inoremap \:deaf_person: 🧏
inoremap \:face_with_monocle: 🧐
inoremap \:adult: 🧑
inoremap \:child: 🧒
inoremap \:older_adult: 🧓
inoremap \:bearded_person: 🧔
inoremap \:person_with_headscarf: 🧕
inoremap \:person_in_steamy_room: 🧖
inoremap \:person_climbing: 🧗
inoremap \:person_in_lotus_position: 🧘
inoremap \:mage: 🧙
inoremap \:fairy: 🧚
inoremap \:vampire: 🧛
inoremap \:merperson: 🧜
inoremap \:elf: 🧝
inoremap \:genie: 🧞
inoremap \:zombie: 🧟
inoremap \:brain: 🧠
inoremap \:orange_heart: 🧡
inoremap \:billed_cap: 🧢
inoremap \:scarf: 🧣
inoremap \:gloves: 🧤
inoremap \:coat: 🧥
inoremap \:socks: 🧦
inoremap \:red_envelope: 🧧
inoremap \:firecracker: 🧨
inoremap \:jigsaw: 🧩
inoremap \:test_tube: 🧪
inoremap \:petri_dish: 🧫
inoremap \:dna: 🧬
inoremap \:compass: 🧭
inoremap \:abacus: 🧮
inoremap \:fire_extinguisher: 🧯
inoremap \:toolbox: 🧰
inoremap \:bricks: 🧱
inoremap \:magnet: 🧲
inoremap \:luggage: 🧳
inoremap \:lotion_bottle: 🧴
inoremap \:thread: 🧵
inoremap \:yarn: 🧶
inoremap \:safety_pin: 🧷
inoremap \:teddy_bear: 🧸
inoremap \:broom: 🧹
inoremap \:basket: 🧺
inoremap \:roll_of_paper: 🧻
inoremap \:soap: 🧼
inoremap \:sponge: 🧽
inoremap \:receipt: 🧾
inoremap \:nazar_amulet: 🧿
inoremap \:ballet_shoes: 🩰
inoremap \:one-piece_swimsuit: 🩱
inoremap \:briefs: 🩲
inoremap \:shorts: 🩳
inoremap \:thong_sandal: 🩴
inoremap \:drop_of_blood: 🩸
inoremap \:adhesive_bandage: 🩹
inoremap \:stethoscope: 🩺
inoremap \:yo-yo: 🪀
inoremap \:kite: 🪁
inoremap \:parachute: 🪂
inoremap \:boomerang: 🪃
inoremap \:magic_wand: 🪄
inoremap \:pinata: 🪅
inoremap \:nesting_dolls: 🪆
inoremap \:ringed_planet: 🪐
inoremap \:chair: 🪑
inoremap \:razor: 🪒
inoremap \:axe: 🪓
inoremap \:diya_lamp: 🪔
inoremap \:banjo: 🪕
inoremap \:military_helmet: 🪖
inoremap \:accordion: 🪗
inoremap \:long_drum: 🪘
inoremap \:coin: 🪙
inoremap \:carpentry_saw: 🪚
inoremap \:screwdriver: 🪛
inoremap \:ladder: 🪜
inoremap \:hook: 🪝
inoremap \:mirror: 🪞
inoremap \:window: 🪟
inoremap \:plunger: 🪠
inoremap \:sewing_needle: 🪡
inoremap \:knot: 🪢
inoremap \:bucket: 🪣
inoremap \:mouse_trap: 🪤
inoremap \:toothbrush: 🪥
inoremap \:headstone: 🪦
inoremap \:placard: 🪧
inoremap \:rock: 🪨
inoremap \:fly: 🪰
inoremap \:worm: 🪱
inoremap \:beetle: 🪲
inoremap \:cockroach: 🪳
inoremap \:potted_plant: 🪴
inoremap \:wood: 🪵
inoremap \:feather: 🪶
inoremap \:anatomical_heart: 🫀
inoremap \:lungs: 🫁
inoremap \:people_hugging: 🫂
inoremap \:blueberries: 🫐
inoremap \:bell_pepper: 🫑
inoremap \:olive: 🫒
inoremap \:flatbread: 🫓
inoremap \:tamale: 🫔
inoremap \:fondue: 🫕
inoremap \:teapot: 🫖

endfunc "end Vythonautos
